import assert from "node:assert/strict";
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import test from "node:test";

const scriptDirectory = dirname(fileURLToPath(import.meta.url)); const checker = resolve(scriptDirectory, "check-evidence-manifest.mjs"); const schema = resolve(scriptDirectory, "../../docs/program/templates/EVIDENCE-MANIFEST.schema.json"); const source = "a".repeat(40); const result = "b".repeat(40); const tree = "c".repeat(64); const ref = "ci://run/fixture";
const privacy = Object.fromEntries(["patientData", "employeePersonData", "identityNumbers", "diagnosisClinicalText", "phone", "email", "detailedFee", "cookie", "token", "password", "apiKeyClientSecret", "privateKeySigningMaterial", "internalHostnameNetwork", "clinicalPromptContent"].map((key) => [key, "CLEAR"]));
test("rejects labeled formatted phones, currency fees, and scheme-agnostic Authorization credentials without leakage", () => { const values = [["patient：Alice", /patient|Alice/i], ["phone: (202) 555-0173", /202|555|0173|phone/i], ["mobile: 202.555.0173", /202|555|0173|mobile/i], ["phone: +1 (202) 555-0173", /202|555|0173|phone/i], ["phone: 202/555/0173", /202|555|0173|phone/i], ["phone：202-555-0173", /202|555|0173|phone/i], ["phone: 202–555–0173", /202|555|0173|phone/i], ["phone: 202‑555‑0173", /202|555|0173|phone/i], ["phone: 202 555 0173", /202|555|0173|phone/i], ["amount: $123.45", /amount|123\.45/i], ["amount: $1,234.56", /amount|1,234\.56/i], ["amount：₹1,234.56", /amount|1,234\.56/i], ["detailed_fee: ￥123.45", /detailed_fee|123\.45/i], ["fee_amount: ¥123.45", /fee_amount|123\.45/i], ["detailed_fee: €1,234.56", /detailed_fee|1,234\.56/i], ["Authorization: Token opaque-fixture", /Authorization|Token|opaque-fixture/i], ["Authorization: Digest opaque-fixture", /Authorization|Digest|opaque-fixture/i], ["Authorization：Token opaque-fixture", /Authorization|Token|opaque-fixture/i]]; for (const [value, redacted] of values) { const output = run(base({ limitations: [value] })); assert.notEqual(output.status, 0, output.stdout); assert.match(output.stdout, /PROHIBITED_PRIVACY_CONTENT/); assert.doesNotMatch(output.stdout, redacted); } });
test("permits ordinary Authorization prose without an assignment separator", () => { for (const value of ["Authorization Bearer tokens require redaction.", "Authorization　Bearer tokens require redaction."]) assert.equal(run(base({ limitations: [value] })).status, 0); });
test("permits a labeled under-length phone fragment", () => { assert.equal(run(base({ limitations: ["phone: 202/555"] })).status, 0); });
const ipv6 = (...parts) => parts.join(":"); const internalIpv6 = [ipv6("FD12", "3456", "789A", "", "1"), ["[", ipv6("fE80", "", "1%Ethernet"), "]"].join(""), ipv6("FC00", ""), ipv6("FdFf", "FfFf", "FfFf", "FfFf", "FfFf", "FfFf", "FfFf", "FfFf"), ipv6("FE80", ""), ipv6("fEbF", "FfFf", "FfFf", "FfFf", "FfFf", "FfFf", "FfFf", "FfFf"), `${ipv6("FC00", "")}/7`, `${ipv6("Fe80", "")}/10`];
function receipt(agent = "terra_reviewer", outcome = "APPROVED", overrides = {}) { return { schemaVersion: "hospital-workspace.review-receipt.v1", reviewerRole: "independent-reviewer", agent, model: "gpt-5.6-terra", reviewType: "implementation", sourceCommit: source, resultCommit: result, resultTree: tree, reviewedDiffBase: source, reviewedDiffHead: result, outcome, limitations: ["Synthetic fixture."], reference: "external://review/fixture", ...overrides }; }
function evidence(status = "NOT_APPLICABLE") { return { status, reference: status === "PASS" ? ref : "not-run://fixture", rationale: "Synthetic fixture.", applicabilityBoundary: "No production system.", reviewerConfirmation: "Confirmed." }; }
function base(overrides = {}) { return { schemaVersion: "hospital-workspace.evidence.v3", program: "hospital-workspace", scope: { kind: "task", phaseId: "HW-00", taskId: "HW00-06" }, risk: "medium", acceptanceTier: "terra", sourceBinding: { kind: "commit", value: source }, resultBinding: { kind: "tree", value: tree }, resultCommit: result, branch: "hw/hw-00/hw00-06-ci-evidence-framework", environments: [{ id: "ubuntu-ci", required: true, status: "PASS", claims: ["ubuntu-ci"], evidenceRefs: [ref] }], requiredCheckIds: ["foundation-checks"], checks: [{ id: "foundation-checks", required: true, environment: "ubuntu-ci", status: "PASS", evidenceRef: ref }], ciArtifacts: [{ name: "report.json", reference: ref, binding: { kind: "tree", value: tree } }], negativeScenarios: [{ id: "negative", status: "PASS", evidenceRef: ref }], rollback: evidence(), recovery: evidence(), rehearsalRequirements: { rollback: false, recovery: false }, requiredReviewAgents: [{ agent: "terra_reviewer", outcome: "APPROVED" }], reviewReceipts: [receipt()], privacyCategories: privacy, dataClassification: "public-synthetic", limitations: ["Synthetic fixture."], decision: "PASS", decisionOwner: "parent_codex", decidedAt: "2026-08-31T00:00:00Z", ...overrides }; }
function run(value, args = [], cwd = null, environment = {}) { const root = mkdtempSync(join(tmpdir(), "hospital-workspace-evidence-")); const path = join(root, "manifest.json"); writeFileSync(path, `${JSON.stringify(value)}\n`); try { return spawnSync(process.execPath, [checker, "--schema", schema, "--manifest", path, ...args], { cwd: cwd ?? root, encoding: "utf8", env: { ...process.env, ...environment } }); } finally { rmSync(root, { recursive: true, force: true }); } }
function runCanonical(args = [], environment = {}) { return spawnSync(process.execPath, [checker, "--template", ...args], { cwd: process.cwd(), encoding: "utf8", env: { ...process.env, ...environment } }); }
function fails(value, pattern, args = []) { const output = run(value, args); assert.notEqual(output.status, 0, output.stdout); assert.match(output.stdout, pattern); }
function git(root, args) { const output = spawnSync("git", args, { cwd: root, encoding: "utf8" }); assert.equal(output.status, 0, output.stderr); return output.stdout.trim(); }
function boundRepository() { const root = mkdtempSync(join(tmpdir(), "hospital-workspace-evidence-git-")); git(root, ["init", "--quiet"]); git(root, ["config", "user.email", "fixture@example.invalid"]); git(root, ["config", "user.name", "Fixture"]); writeFileSync(join(root, "fixture.txt"), "source\n"); git(root, ["add", "fixture.txt"]); git(root, ["commit", "--quiet", "-m", "source"]); const sourceCommit = git(root, ["rev-parse", "HEAD"]); const sourceTree = git(root, ["rev-parse", "HEAD^{tree}"]); writeFileSync(join(root, "fixture.txt"), "result\n"); git(root, ["add", "fixture.txt"]); git(root, ["commit", "--quiet", "-m", "result"]); return { root, sourceCommit, sourceTree, resultCommit: git(root, ["rev-parse", "HEAD"]), resultTree: git(root, ["rev-parse", "HEAD^{tree}"]) }; }
function withBindings(bindings, overrides = {}) { const review = receipt("terra_reviewer", "APPROVED", { sourceCommit: bindings.sourceCommit, resultCommit: bindings.resultCommit, resultTree: bindings.resultTree, reviewedDiffBase: bindings.sourceCommit, reviewedDiffHead: bindings.resultCommit }); return base({ sourceBinding: { kind: "commit", value: bindings.sourceCommit }, resultBinding: { kind: "tree", value: bindings.resultTree }, resultCommit: bindings.resultCommit, reviewReceipts: [review], ciArtifacts: [{ name: "report.json", reference: ref, binding: { kind: "tree", value: bindings.resultTree } }], ...overrides }); }
test("accepts valid low-risk external Terra receipt and medium-risk CI receipt", () => { assert.equal(run(base({ risk: "low", ciArtifacts: [] })).status, 0); assert.equal(run(base()).status, 0); });
test("canonical template validation passes locally and in CI only without custom inputs", () => { const local = runCanonical(); assert.equal(local.status, 0, local.stdout); const ci = runCanonical([], { CI: "true" }); assert.equal(ci.status, 0, ci.stdout); });
test("template mode rejects custom manifest/schema, CI flag, and trusted inputs", () => { const custom = run(base(), ["--template"]); assert.notEqual(custom.status, 0, custom.stdout); assert.match(custom.stdout, /EVIDENCE_MANIFEST_CHECK_ERROR/); for (const args of [["--ci"], ["--schema", schema], ["--expected-source-commit", source], ["--expected-rollback-rehearsal", "not-required"], ["--expected-recovery-rehearsal", "not-required"]]) { const output = runCanonical(args); assert.notEqual(output.status, 0, output.stdout); assert.match(output.stdout, /EVIDENCE_MANIFEST_CHECK_ERROR/); } });
test("a real manifest under CI cannot bypass trusted inputs without template mode", () => { const output = run(base(), [], process.cwd(), { CI: "true" }); assert.notEqual(output.status, 0, output.stdout); assert.match(output.stdout, /TRUSTED_BINDING_REQUIRED/); assert.match(output.stdout, /TRUSTED_REHEARSAL_EXPECTATION_REQUIRED/); });
test("accepts high-risk PASS with rollback and recovery", () => { const sol = receipt("sol_acceptance", "ACCEPT"); assert.equal(run(base({ risk: "high", acceptanceTier: "sol-acceptance", rollback: evidence("PASS"), recovery: evidence("PASS"), requiredReviewAgents: [{ agent: "terra_reviewer", outcome: "APPROVED" }, { agent: "sol_acceptance", outcome: "ACCEPT" }], reviewReceipts: [receipt(), sol] })).status, 0); });
test("a non-template manifest in a Git repository validates actual objects without trusted flags", () => { const repository = boundRepository(); try { const missing = run(base(), [], repository.root); assert.notEqual(missing.status, 0, missing.stdout); assert.match(missing.stdout, /SOURCE_GIT_OBJECT_MISSING/); assert.match(missing.stdout, /RESULT_COMMIT_GIT_OBJECT_MISSING/); assert.match(missing.stdout, /RESULT_TREE_GIT_OBJECT_MISSING/); const valid = run(withBindings(repository), [], repository.root); assert.equal(valid.status, 0, valid.stdout); } finally { rmSync(repository.root, { recursive: true, force: true }); } });
test("Git-reported bare and inherited Git-directory contexts validate actual objects", () => { const repository = boundRepository(); const bare = mkdtempSync(join(tmpdir(), "hospital-workspace-evidence-bare-")); const context = mkdtempSync(join(tmpdir(), "hospital-workspace-evidence-context-")); try { git(bare, ["init", "--bare", "--quiet"]); let output = run(base(), [], bare); assert.notEqual(output.status, 0, output.stdout); assert.match(output.stdout, /SOURCE_GIT_OBJECT_MISSING/); const environment = { GIT_DIR: join(repository.root, ".git"), GIT_WORK_TREE: repository.root }; output = run(base(), [], context, environment); assert.notEqual(output.status, 0, output.stdout); assert.match(output.stdout, /SOURCE_GIT_OBJECT_MISSING/); output = run(withBindings(repository), [], context, environment); assert.equal(output.status, 0, output.stdout); } finally { rmSync(repository.root, { recursive: true, force: true }); rmSync(bare, { recursive: true, force: true }); rmSync(context, { recursive: true, force: true }); } });
test("high PASS missing recovery and critical PASS missing rollback fail", () => { fails(base({ risk: "high", acceptanceTier: "sol-acceptance", recovery: evidence("NOT_RUN") }), /RECOVERY|REQUIRED/); fails(base({ risk: "critical", acceptanceTier: "sol-architecture-security", rollback: evidence("NOT_RUN"), requiredReviewAgents: [{ agent: "terra_reviewer", outcome: "APPROVED" }, { agent: "sol_architecture_security", outcome: "ACCEPT" }], reviewReceipts: [receipt(), receipt("sol_architecture_security", "ACCEPT")] }), /ROLLBACK|REQUIRED/); });
test("PASS rollback and recovery reject unexecuted references for high and critical Evidence", () => { const unexecuted = { ...evidence("PASS"), reference: "not-run://fixture" }; for (const risk of ["high", "critical"]) for (const field of ["rollback", "recovery"]) fails(base({ risk, acceptanceTier: risk === "high" ? "sol-acceptance" : "sol-architecture-security", [field]: unexecuted }), /PASS_REFERENCE_NOT_EXECUTED/); });
test("PASS status rejects unexecuted references on every executed Evidence surface", () => { const unexecuted = "not-run://fixture"; for (const overrides of [{ environments: [{ ...base().environments[0], evidenceRefs: [unexecuted] }] }, { checks: [{ ...base().checks[0], evidenceRef: unexecuted }] }, { negativeScenarios: [{ ...base().negativeScenarios[0], evidenceRef: unexecuted }] }, { ciArtifacts: [{ ...base().ciArtifacts[0], reference: unexecuted }] }, { reviewReceipts: [receipt("terra_reviewer", "APPROVED", { reference: unexecuted })] }]) fails(base(overrides), /PASS_REFERENCE_NOT_EXECUTED/); });
test("trusted external binding rejects a self-consistent stale manifest", () => { const stale = base({ resultCommit: "d".repeat(40), resultBinding: { kind: "tree", value: "e".repeat(64) }, reviewReceipts: [receipt("terra_reviewer", "APPROVED", { resultCommit: "d".repeat(40), resultTree: "e".repeat(64), reviewedDiffHead: "d".repeat(40) })], ciArtifacts: [{ name: "report.json", reference: ref, binding: { kind: "tree", value: "e".repeat(64) } }] }); const output = run(stale, ["--expected-source-commit", source, "--expected-result-commit", result, "--expected-result-tree", tree]); assert.notEqual(output.status, 0, output.stdout); assert.match(output.stdout, /TRUSTED/); });
test("non-CI trusted binding requires a complete source, result, and tree tuple", () => { const partials = [["--expected-source-commit", "d".repeat(40)], ["--expected-result-commit", result], ["--expected-result-tree", tree], ["--expected-source-commit", source, "--expected-result-commit", result], ["--expected-source-commit", source, "--expected-result-tree", tree], ["--expected-result-commit", result, "--expected-result-tree", tree]]; for (const args of partials) { const output = run(base(), args); assert.notEqual(output.status, 0, output.stdout); assert.match(output.stdout, /TRUSTED_BINDING_INCOMPLETE/); } const complete = run(base(), ["--expected-source-commit", source, "--expected-result-commit", result, "--expected-result-tree", tree]); assert.equal(complete.status, 0, complete.stdout); });
test("CI mode requires trusted bindings and both rehearsal expectations", () => { const output = run(base(), ["--ci"]); assert.notEqual(output.status, 0); assert.match(output.stdout, /TRUSTED_BINDING_REQUIRED/); assert.match(output.stdout, /TRUSTED_REHEARSAL_EXPECTATION_REQUIRED/); });
test("CI mode accepts matching not-required trusted rehearsal expectations", () => { const repository = boundRepository(); try { const args = ["--ci", "--expected-source-commit", repository.sourceCommit, "--expected-result-commit", repository.resultCommit, "--expected-result-tree", repository.resultTree, "--expected-rollback-rehearsal", "not-required", "--expected-recovery-rehearsal", "not-required"]; const output = run(withBindings(repository), args, repository.root); assert.equal(output.status, 0, output.stdout); } finally { rmSync(repository.root, { recursive: true, force: true }); } });
test("CI mode rejects missing rehearsal expectations even with trusted Git bindings", () => { const repository = boundRepository(); try { const output = run(withBindings(repository), ["--ci", "--expected-source-commit", repository.sourceCommit, "--expected-result-commit", repository.resultCommit, "--expected-result-tree", repository.resultTree], repository.root); assert.notEqual(output.status, 0, output.stdout); assert.match(output.stdout, /TRUSTED_REHEARSAL_EXPECTATION_REQUIRED/); } finally { rmSync(repository.root, { recursive: true, force: true }); } });
test("CI trusted rehearsal inputs reject malformed, mismatched, and required NOT_APPLICABLE declarations", () => { const repository = boundRepository(); try { const bindings = ["--ci", "--expected-source-commit", repository.sourceCommit, "--expected-result-commit", repository.resultCommit, "--expected-result-tree", repository.resultTree]; let output = run(withBindings(repository), [...bindings, "--expected-rollback-rehearsal", "maybe", "--expected-recovery-rehearsal", "not-required"], repository.root); assert.notEqual(output.status, 0, output.stdout); assert.match(output.stdout, /INVALID_TRUSTED_REHEARSAL_EXPECTATION/); output = run(withBindings(repository), [...bindings, "--expected-rollback-rehearsal", "required", "--expected-recovery-rehearsal", "not-required"], repository.root); assert.notEqual(output.status, 0, output.stdout); assert.match(output.stdout, /TRUSTED_REHEARSAL_EXPECTATION_MISMATCH/); const required = withBindings(repository, { risk: "high", acceptanceTier: "sol-acceptance", rehearsalRequirements: { rollback: true, recovery: false }, rollback: evidence("NOT_APPLICABLE"), recovery: evidence("PASS") }); output = run(required, [...bindings, "--expected-rollback-rehearsal", "required", "--expected-recovery-rehearsal", "not-required"], repository.root); assert.notEqual(output.status, 0, output.stdout); assert.match(output.stdout, /NOT_APPLICABLE_REHEARSAL_NOT_PERMITTED/); } finally { rmSync(repository.root, { recursive: true, force: true }); } });
test("legacy one-way rehearsal switches are unsupported", () => { const output = run(base(), ["--rollback-rehearsal-required"]); assert.notEqual(output.status, 0, output.stdout); assert.match(output.stdout, /EVIDENCE_MANIFEST_CHECK_ERROR/); });
test("trusted binding rejects a missing result commit and a mismatched commit tree", () => { const repository = boundRepository(); try { const missing = "f".repeat(40); const missingBindings = { ...repository, resultCommit: missing }; const rehearsal = ["--expected-rollback-rehearsal", "not-required", "--expected-recovery-rehearsal", "not-required"]; let output = run(withBindings(missingBindings), ["--ci", "--expected-source-commit", repository.sourceCommit, "--expected-result-commit", missing, "--expected-result-tree", repository.resultTree, ...rehearsal], repository.root); assert.notEqual(output.status, 0, output.stdout); assert.match(output.stdout, /RESULT_COMMIT_GIT_OBJECT_MISSING/); const wrongTree = { ...repository, resultTree: repository.sourceTree }; output = run(withBindings(wrongTree), ["--ci", "--expected-source-commit", repository.sourceCommit, "--expected-result-commit", repository.resultCommit, "--expected-result-tree", repository.sourceTree, ...rehearsal], repository.root); assert.notEqual(output.status, 0, output.stdout); assert.match(output.stdout, /RESULT_COMMIT_TREE_MISMATCH/); } finally { rmSync(repository.root, { recursive: true, force: true }); } });
for (const [name, mutate] of [["model", (r) => { delete r.model; }], ["review type", (r) => { delete r.reviewType; }], ["source commit", (r) => { delete r.sourceCommit; }]]) test(`rejects receipt missing ${name}`, () => { const r = receipt(); mutate(r); fails(base({ reviewReceipts: [r] }), /RECEIPT/); });
test("rejects unknown manifest, receipt, and review-type schema values", () => { fails(base({ schemaVersion: "hospital-workspace.evidence.v999" }), /SCHEMA/); fails(base({ reviewReceipts: [receipt("terra_reviewer", "APPROVED", { schemaVersion: "hospital-workspace.review-receipt.v999" })] }), /RECEIPT/); fails(base({ reviewReceipts: [receipt("terra_reviewer", "APPROVED", { reviewType: "unknown" })] }), /RECEIPT/); });
test("rejects missing privacy category", () => { const categories = { ...privacy }; delete categories.phone; fails(base({ privacyCategories: categories }), /PRIVACY/); });
for (const value of [
  [["patient", "name"].join("_"), "synthetic-person"].join("="),
  [["employee", "id"].join("_"), "synthetic-worker"].join("="),
  [["identity", "number"].join("_"), "11010519491231002X"].join("="),
  [["diagnosis"], "synthetic-clinical-text"].join("="),
  [["phone"], "13800138000"].join("="),
  "fixture@example.org",
  [["detailed", "fee"].join("_"), "123.45"].join("="),
  [["cookie"], "abcdefgh"].join("="),
  [["access", "token"].join("_"), "abcdefgh"].join("="),
  [["password"], "abcdefgh"].join("="),
  [["client", "secret"].join("_"), "abcdefgh"].join("="),
  [["private", "key"].join("_"), "abcdefgh"].join("="),
  ["10", "9", "8", "7"].join("."),
  [["clinical", "prompt"].join("_"), "synthetic clinical content"].join("=")
]) test("rejects prohibited privacy content", () => { fails(base({ limitations: [value] }), /PRIVACY/); });
for (const [name, value] of [
  ["unkeyed phone", ["Call", "13800138000"].join(" ")],
  ["clinical prompt prose", [["Clinical", "prompt", "content:"].join(" "), "patient-specific details"].join(" ")],
  ["detailed fee prose", [["Detailed", "fee:"].join(" "), "123.45"].join(" ")],
  ["diagnosis clinical prose", [["Diagnosis", "clinical", "text:"].join(" "), "acute condition"].join(" ")],
  ["Bearer JWT-shaped token", [["Bearer"], ["header", "payload", "signature"].join(".")].flat().join(" ")],
  ["Authorization Bearer opaque token", [["Authorization:"], ["opaque", "synthetic", "token"].join("-")].flat().join(" Bearer ")],
  ["Authorization Bearer JWT-shaped token", [["Authorization:"], ["header", "payload", "signature"].join(".")].flat().join(" Bearer ")],
  ["Authorization Basic opaque token", [["Authorization:"], ["opaque", "synthetic", "token"].join("-")].flat().join(" Basic ")],
  ["Authorization Bearer one-character token", [["Authorization:"], "x"].flat().join(" Bearer ")],
  ["Authorization Basic one-character token", [["Authorization:"], "x"].flat().join(" Basic ")],
  ["JWT secret snake", [["jwt", "secret"].join("_"), "abcdefgh"].join("=")],
  ["JWT secret camel", [["jwt", "Secret"].join(""), "abcdefgh"].join("=")],
  ["generic secret", ["secret", "abcdefgh"].join("=")],
  ["credential sentinel still prohibited", ["secret", "example"].join("=")],
  ["unkeyed E.164 phone", ["Call", "+12025550173"].join(" ")],
  ["ULA IPv6", internalIpv6[0]],
  ["link-local IPv6 zone", internalIpv6[1]],
  ["direct patient label", ["Patient", "Alice"].join(": ")],
  ["direct employee label", ["employee", "Alice"].join(" = ")],
  ["direct person label", ["person", "Alice"].join(": ")],
  ["Patient Name label", [["Patient", "Name:"].join(" "), ["Synthetic", "Person"].join(" ")].join(" ")],
  ["Employee Name label", [["Employee", "Name:"].join(" "), ["Synthetic", "Person"].join(" ")].join(" ")],
  ["PGP private-key armor", [["-----BEGIN", "PGP", "PRIVATE", "KEY", "BLOCK-----"].join(" ")].join("")]
]) test(`rejects human-readable prohibited privacy content: ${name}`, () => { fails(base({ limitations: [value] }), /PRIVACY/); });
test("does not expose labeled authorization or E.164 values in manifest output", () => { for (const value of [[["Authorization:"], "x"].flat().join(" Bearer "), ["Call", "+12025550173"].join(" ")]) { const output = run(base({ limitations: [value] })); assert.notEqual(output.status, 0, output.stdout); assert.match(output.stdout, /PROHIBITED_PRIVACY_CONTENT/); assert.doesNotMatch(output.stdout, /Authorization|Bearer|12025550173/); } });
test("does not expose JWT or generic secret assignment values in manifest output", () => { const jwt = ["jwt", "secret"].join("_"); const generic = ["secret", "="].join(""); const redacted = new RegExp(["abcdefgh", jwt, generic].join("|"), "i"); for (const value of [[jwt, "abcdefgh"].join("="), ["secret", "abcdefgh"].join("=")]) { const output = run(base({ limitations: [value] })); assert.notEqual(output.status, 0, output.stdout); assert.match(output.stdout, /PROHIBITED_PRIVACY_CONTENT/); assert.doesNotMatch(output.stdout, redacted); } });
test("does not expose direct patient, employee, or person labels in manifest output", () => { for (const value of [["Patient", "Alice"].join(": "), ["employee", "Alice"].join(" = "), ["person", "Alice"].join(": ")]) { const output = run(base({ limitations: [value] })); assert.notEqual(output.status, 0, output.stdout); assert.match(output.stdout, /PROHIBITED_PRIVACY_CONTENT/); assert.doesNotMatch(output.stdout, /Alice|Patient|employee|person/i); } });
test("permits ordinary prose that mentions Authorization Bearer without a credential value", () => { assert.equal(run(base({ limitations: [["Authorization", "Bearer", "tokens", "require", "redaction."].join(" ")] })).status, 0); });
test("permits ordinary policy prose that mentions patient, employee, and person without an assignment", () => { assert.equal(run(base({ limitations: [["Patient", "employee", "and", "person", "data", "remain", "prohibited."].join(" ")] })).status, 0); });
test("permits public and documentation IPv6 addresses", () => { for (const value of ["2001:db8::1", "2001:4860:4860::8888"]) assert.equal(run(base({ limitations: [value] })).status, 0); });
test("rejects compressed, full, bracketed, zoned, and CIDR ULA or link-local IPv6", () => { for (const value of internalIpv6) fails(base({ limitations: [value] }), /PRIVACY/); });
test("permits IPv6 values immediately outside ULA and link-local ranges", () => { for (const value of [ipv6("FBFF", "", "1"), ipv6("FEC0", "", "1"), "2001:db8::1", "2001:4860:4860::8888"]) assert.equal(run(base({ limitations: [value] })).status, 0); });
test("rejects invalid Linux, WSL, and mock environment claims", () => { for (const env of [{ id: "ubuntu-ci", required: true, status: "PASS", claims: ["ubuntu-ci", "windows-tauri-webview2-msi"], evidenceRefs: [ref] }, { id: "wsl2", required: false, status: "PASS", claims: ["physical-anolis"], evidenceRefs: [ref] }, { id: "mock-integration", required: false, status: "PASS", claims: ["mock-integration", "real-upstream-his"], evidenceRefs: [ref] }]) fails(base({ environments: [env] }), /OVERCLAIM/); });
