import assert from "node:assert/strict";
import { mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import test from "node:test";

const checker = resolve(dirname(fileURLToPath(import.meta.url)), "check-public-safety.mjs");
function write(root, path, content) { const file = join(root, path); mkdirSync(dirname(file), { recursive: true }); writeFileSync(file, content); }
function run(root, ...args) { return spawnSync(process.execPath, [checker, "--root", root, ...args], { encoding: "utf8" }); }
function fixture(setup) { const root = mkdtempSync(join(tmpdir(), "hospital-workspace-public-safety-")); try { setup(root); return run(root); } finally { rmSync(root, { recursive: true, force: true }); } }
function assertRule(result, path, rule) { assert.notEqual(result.status, 0, result.stdout); const report = JSON.parse(result.stdout); assert.ok(report.findings.some((finding) => finding.path === path && finding.rule === rule), result.stdout); assert.ok(report.findings.every((finding) => Object.keys(finding).sort().join(",") === "path,rule"), result.stdout); }
function indexCacheInfo(root, mode, path, content) { const initialized = spawnSync("git", ["init", "--quiet"], { cwd: root, encoding: "utf8" }); assert.equal(initialized.status, 0, initialized.stderr); const hashed = spawnSync("git", ["hash-object", "-w", "--stdin"], { cwd: root, input: content, encoding: "utf8" }); assert.equal(hashed.status, 0, hashed.stderr); const updated = spawnSync("git", ["update-index", "--add", "--cacheinfo", `${mode},${hashed.stdout.trim()},${path}`], { cwd: root, encoding: "utf8" }); assert.equal(updated.status, 0, updated.stderr); }
const credential = (key, value = "abcdefgh") => `${JSON.stringify(key)}:${JSON.stringify(value)}`;
const escapedCredentialKey = ["\\", "u0061", "pi_key"].join(""); const escapedNonCredentialKey = ["\\", "u0066", "oo"].join("");
const escapedKey = (escape) => ["\\", escape, "pi_key"].join("");
const tick = String.fromCharCode(96); const doubleQuote = String.fromCharCode(34); const apostrophe = String.fromCharCode(39);
const privateKeyMarker = ["-----BEGIN", "PRIVATE", "KEY-----"].join(" ");
const pgpPrivateKeyMarker = ["-----BEGIN", "PGP", "PRIVATE", "KEY", "BLOCK-----"].join(" ");
const privateNetwork = ["10", "4", "5", "6"].join(".");
test("rejects JSON Schema-shaped credential objects outside the exact exception", () => { const key = ["pass", "word"].join(""); const quote = String.fromCharCode(34); const result = fixture((root) => write(root, "schema.json", `{ ${quote}properties${quote}: { ${quote}${key}${quote}: { ${quote}const${quote}: ${quote}CLEAR${quote} } } }`)); assertRule(result, "schema.json", "CREDENTIAL_ASSIGNMENT_PATTERN"); assert.doesNotMatch(result.stdout, /CLEAR/); });
test("permits only the exact schema path, rule, and content hash exception", () => { const path = ["docs", "program", "templates", "EVIDENCE-MANIFEST.schema.json"].join("/"); const bytes = readFileSync(resolve(dirname(checker), "..", "..", path)); const exact = fixture((root) => write(root, path, bytes)); assert.equal(exact.status, 0, exact.stdout); const mutated = fixture((root) => write(root, path, Buffer.concat([bytes, Buffer.from("\n")]))); assertRule(mutated, path, "CREDENTIAL_ASSIGNMENT_PATTERN"); });
test("rejects a multiline JSON credential from the Git index without leaking it", () => { const root = mkdtempSync(join(tmpdir(), "hospital-workspace-public-safety-index-multiline-json-")); try { const snake = ["api", "key"].join("_"); const line = String.fromCharCode(10); const quote = String.fromCharCode(34); write(root, "fixture.json", ["{", `  ${quote}${snake}${quote}`, "  :", `  ${quote}abcdefgh${quote}`, "}"].join(line)); spawnSync("git", ["init", "--quiet"], { cwd: root }); spawnSync("git", ["add", "fixture.json"], { cwd: root }); write(root, "fixture.json", "safe"); const result = run(root, "--git-index"); assertRule(result, "fixture.json", "CREDENTIAL_ASSIGNMENT_PATTERN"); assert.doesNotMatch(result.stdout, /abcdefgh/); } finally { rmSync(root, { recursive: true, force: true }); } });
test("rejects multiline JSON and JavaScript credential assignments without leaking values", () => { const snake = ["api", "key"].join("_"); const camel = ["api", "Key"].join(""); const line = String.fromCharCode(10); const quote = String.fromCharCode(34); const result = fixture((root) => { write(root, "fixture.json", ["{", `  ${quote}${snake}${quote}`, "  :", `  ${quote}abcdefgh${quote}`, "}"].join(line)); write(root, "fixture.ts", [`const ${camel}`, "=", `${quote}abcdefgh${quote};`, `config[${quote}${camel}${quote}]`, "=", "abcdefg;"].join(line)); }); assertRule(result, "fixture.json", "CREDENTIAL_ASSIGNMENT_PATTERN"); assertRule(result, "fixture.ts", "CREDENTIAL_ASSIGNMENT_PATTERN"); assert.doesNotMatch(result.stdout, /abcdefgh|abcdefg/); });
test("rejects indented YAML quoted and plain credential values without leaking them", () => { const snake = ["api", "key"].join("_"); const token = ["auth", "token"].join("_"); const line = String.fromCharCode(10); const quote = String.fromCharCode(34); const result = fixture((root) => write(root, "fixture.yaml", [`${snake}:`, `  ${quote}abcdefgh${quote}`, `${token}:`, "  abcdefgh"].join(line))); assertRule(result, "fixture.yaml", "CREDENTIAL_ASSIGNMENT_PATTERN"); assert.doesNotMatch(result.stdout, /abcdefgh/); });
test("accepts multiline empty and approved credential sentinels without borrowing a same-indent YAML mapping", () => { const snake = ["api", "key"].join("_"); const camel = ["api", "Key"].join(""); const line = String.fromCharCode(10); const quote = String.fromCharCode(34); const result = fixture((root) => { write(root, "fixture.json", ["{", `  ${quote}${snake}${quote}`, "  :", `  ${quote}${quote}`, "}"].join(line)); write(root, "fixture.ts", [`const ${camel}`, "=", "example;"].join(line)); write(root, "fixture.yaml", [`${snake}:`, "  synthetic", `${snake}:`, "safe: example"].join(line)); }); assert.equal(result.status, 0, result.stdout); });
test("rejects JSON object and array credential values", () => { const snake = ["api", "key"].join("_"); const token = ["auth", "token"].join("_"); const quote = String.fromCharCode(34); const result = fixture((root) => write(root, "fixture.json", `{ ${quote}${snake}${quote}: { ${quote}nested${quote}: ${quote}example${quote} }, ${quote}${token}${quote}: [${quote}example${quote}] }`)); assertRule(result, "fixture.json", "CREDENTIAL_ASSIGNMENT_PATTERN"); assert.doesNotMatch(result.stdout, /nested|example/); });
const ipv6 = (...parts) => parts.join(":"); const internalIpv6 = [ipv6("FD12", "3456", "789A", "", "1"), ipv6("FDFF", "FFFF", "FFFF", "FFFF", "FFFF", "FFFF", "FFFF", "FFFF"), ["[", ipv6("fE80", "", "1%Ethernet"), "]"].join(""), `${ipv6("FC00", "")}/7`, `${ipv6("Fe80", "")}/10`];
const portalAlias = ["@", "portal", "/", "fixture"].join("");
const legacyCopyMarker = ["LEGACY", "SOURCE", "COPY"].join("_");
const formats = [
  ["json", (key) => `{${credential(key)}}\n`], ["yaml", (key) => `${key}: \"abcdefgh\"\n`], ["toml", (key) => `${key} = \"abcdefgh\"\n`], ["typescript", (key) => `const ${key} = \"abcdefgh\";\n`], ["shell", (key) => `${key.toUpperCase()}=\"abcdefgh\"\n`]
];
test("accepts deterministic public and approved non-secret sentinels", () => { const result = fixture((root) => { write(root, "README.md", "Example Hospital\n"); write(root, "config/.env.example", "API_KEY=\"example\"\n"); }); assert.equal(result.status, 0, result.stdout); });
test("accepts empty quoted credential assignments", () => { const result = fixture((root) => write(root, "config/example.json", `{${credential(["api", "key"].join("_"), "")}}\n`)); assert.equal(result.status, 0, result.stdout); });
test("rejects ordinary unquoted credential assignments across shell, YAML, and TypeScript", () => { const snake = ["api", "key"].join("_"); const camel = ["api", "Key"].join(""); const token = ["auth", "token"].join("_"); const tokenCamel = ["auth", "Token"].join(""); const bare = ["abc", "defgh"].join(""); const result = fixture((root) => { write(root, "fixture.env", `export ${snake.toUpperCase()}=${bare}\n${snake.toUpperCase()}=${bare}\n${snake.toUpperCase()}=\${${bare}}\n`); write(root, "fixture.yaml", `${snake}: ${bare}\n${token}: !vault ${bare}\n`); write(root, "fixture.ts", `const ${camel} = ${bare};\nconst ${tokenCamel}: string = ${bare};\nconst config = { [\"${snake}\"]: ${bare} } as const;\nconfig[\"${camel}\"] = ${bare};\n`); }); assertRule(result, "fixture.env", "CREDENTIAL_ASSIGNMENT_PATTERN"); assertRule(result, "fixture.yaml", "CREDENTIAL_ASSIGNMENT_PATTERN"); assertRule(result, "fixture.ts", "CREDENTIAL_ASSIGNMENT_PATTERN"); assert.doesNotMatch(result.stdout, /abcdefgh/); });
test("accepts empty and approved unquoted credential values and alias-to-sentinel", () => { const snake = ["api", "key"].join("_"); const camel = ["api", "Key"].join(""); const token = ["auth", "token"].join("_"); const tokenCamel = ["auth", "Token"].join(""); const result = fixture((root) => { write(root, "fixture.env", `${snake.toUpperCase()}=\nexport ${snake.toUpperCase()}=example\n`); write(root, "fixture.yaml", `${snake}: example\n${token}: !vault synthetic\nmemo: &sentinel \"example\"\n${snake}: *sentinel\n`); write(root, "fixture.ts", `const ${camel} = example;\nconst ${tokenCamel}: string = synthetic;\nconfig[\"${camel}\"] = example;\n`); }); assert.equal(result.status, 0, result.stdout); });
test("rejects a YAML plain scalar containing an equals sign despite a sentinel suffix", () => { const snake = ["api", "key"].join("_"); const value = ["abc", "=", "example"].join(""); const result = fixture((root) => write(root, "fixture.yaml", `${snake}: ${value}\n`)); assertRule(result, "fixture.yaml", "CREDENTIAL_ASSIGNMENT_PATTERN"); assert.doesNotMatch(result.stdout, /abc=example/); });
test("rejects unquoted object and array credential expressions in TypeScript", () => { const camel = ["api", "Key"].join(""); const snake = ["auth", "token"].join("_"); const result = fixture((root) => write(root, "fixture.ts", `const ${camel} = { nested: example };\nconfig[\"${camel}\"] = [example];\nconst values = { [\"${snake}\"]: call(example) } as const;\n`)); assertRule(result, "fixture.ts", "CREDENTIAL_ASSIGNMENT_PATTERN"); assert.doesNotMatch(result.stdout, /nested|call\(example\)/); });
test("accepts class TypeScript typed empty and approved credential sentinels", () => { const camel = ["api", "Key"].join(""); const token = ["auth", "Token"].join(""); const result = fixture((root) => write(root, "fixture.ts", `class Fixture {\n  ${camel}: string = \"example\";\n  ${token}!: string = \"\";\n}\n`)); assert.equal(result.status, 0, result.stdout); });
test("fails closed for unresolved credential YAML aliases", () => { const snake = ["api", "key"].join("_"); const result = fixture((root) => write(root, "fixture.yaml", `${snake}: *unknown\n`)); assertRule(result, "fixture.yaml", "CREDENTIAL_ASSIGNMENT_PATTERN"); });
test("rejects an unquoted credential from the Git index without leaking its value", () => { const root = mkdtempSync(join(tmpdir(), "hospital-workspace-public-safety-index-unquoted-")); try { const camel = ["api", "Key"].join(""); const bare = ["abc", "defgh"].join(""); write(root, "fixture.ts", `config[\"${camel}\"] = ${bare};\n`); spawnSync("git", ["init", "--quiet"], { cwd: root }); spawnSync("git", ["add", "fixture.ts"], { cwd: root }); write(root, "fixture.ts", "safe\n"); const result = run(root, "--git-index"); assertRule(result, "fixture.ts", "CREDENTIAL_ASSIGNMENT_PATTERN"); assert.doesNotMatch(result.stdout, /abcdefgh/); } finally { rmSync(root, { recursive: true, force: true }); } });
test("rejects a YAML equals-bearing credential scalar from the Git index without leaking it", () => { const root = mkdtempSync(join(tmpdir(), "hospital-workspace-public-safety-index-yaml-equals-")); try { const snake = ["api", "key"].join("_"); const value = ["abc", "=", "example"].join(""); write(root, "fixture.yaml", `${snake}: ${value}\n`); spawnSync("git", ["init", "--quiet"], { cwd: root }); spawnSync("git", ["add", "fixture.yaml"], { cwd: root }); write(root, "fixture.yaml", "safe\n"); const result = run(root, "--git-index"); assertRule(result, "fixture.yaml", "CREDENTIAL_ASSIGNMENT_PATTERN"); assert.doesNotMatch(result.stdout, /abc=example/); } finally { rmSync(root, { recursive: true, force: true }); } });
test("rejects static computed JavaScript and TypeScript credential keys without leaking values", () => { const key = ["api", "key"].join("_"); const camel = ["api", "Key"].join(""); const escaped = ["\\", "u0061", "piKey"].join(""); const result = fixture((root) => write(root, "fixture.ts", `const object = { [\"${key}\"]: \"abcdefgh\", ['${key}']: \"abcdefgh\", [${tick}${key}${tick}]: \"abcdefgh\" } as const;\nconfig[\"${camel}\"] = \"abcdefgh\";\nconfig[ /* synthetic */ \"${camel}\" /* synthetic */ ] = \"abcdefgh\";\nconfig[\"${escaped}\"] = \"abcdefgh\";\nconst typed: Record<string, string> = { [\"${camel}\"]: \"abcdefgh\" } as const;\n`)); assertRule(result, "fixture.ts", "CREDENTIAL_ASSIGNMENT_PATTERN"); assert.doesNotMatch(result.stdout, /abcdefgh/); });
test("accepts empty and approved static computed credential-key values", () => { const key = ["api", "key"].join("_"); const camel = ["api", "Key"].join(""); const result = fixture((root) => write(root, "fixture.ts", `const object = { [\"${key}\"]: \"\", ['${key}']: \"example\", [${tick}${key}${tick}]: \"synthetic\" };\nconfig[\"${camel}\"] = \"\";\nconfig[ /* synthetic */ \"${camel}\" ] = \"example\";\n`)); assert.equal(result.status, 0, result.stdout); });
test("rejects a static computed credential key from the Git index without leaking its value", () => { const root = mkdtempSync(join(tmpdir(), "hospital-workspace-public-safety-index-computed-")); try { const camel = ["api", "Key"].join(""); write(root, "fixture.ts", `config[\"${camel}\"] = \"abcdefgh\";\n`); spawnSync("git", ["init", "--quiet"], { cwd: root }); spawnSync("git", ["add", "fixture.ts"], { cwd: root }); write(root, "fixture.ts", "safe\n"); const result = run(root, "--git-index"); assertRule(result, "fixture.ts", "CREDENTIAL_ASSIGNMENT_PATTERN"); assert.doesNotMatch(result.stdout, /abcdefgh/); } finally { rmSync(root, { recursive: true, force: true }); } });
test("rejects the required JSON credential assignment without leaking its value", () => { const result = fixture((root) => write(root, "fixture.json", `{${credential(["api", "key"].join("_"))}}\n`)); assertRule(result, "fixture.json", "CREDENTIAL_ASSIGNMENT_PATTERN"); assert.doesNotMatch(result.stdout, /abcdefgh/); });
test("rejects delimiter-specific quoted and template credential values without leaking values", () => { const key = ["api", "key"].join("_"); const camel = ["api", "Key"].join(""); const quoteInDouble = ["foo", "\\", doubleQuote, "bar"].join(""); const quoteInSingle = ["foo", doubleQuote, "bar"].join(""); const interpolation = ["$", "{", "fixture", "}"].join(""); for (const [path, content] of [["quoted.json", `{${credential(key, ["foo", apostrophe, "bar"].join(""))}}\n`], ["escaped.json", `{${credential(key, quoteInDouble)}}\n`], ["quoted.yaml", `${key}: ${apostrophe}${quoteInSingle}${apostrophe}\n`], ["quoted.sh", `${key.toUpperCase()}=${apostrophe}${quoteInSingle}${apostrophe}\n`], ["template.ts", ["const", camel, "=", `${tick}${interpolation}${tick};`].join(" ")]]) { const result = fixture((root) => write(root, path, content)); assertRule(result, path, "CREDENTIAL_ASSIGNMENT_PATTERN"); assert.doesNotMatch(result.stdout, /foo|fixture/); } });
test("accepts empty and exact sentinel values across quoted delimiters", () => { const key = ["api", "key"].join("_"); const camel = ["api", "Key"].join(""); const tokenCamel = ["auth", "Token"].join(""); const result = fixture((root) => write(root, "quoted.ts", `{${credential(key, "")}\n${key}: ${apostrophe}${apostrophe}\n${key.toUpperCase()}=${apostrophe}example${apostrophe}\nconst ${camel} = ${tick}${tick};\nconst ${tokenCamel}: string = ${tick}synthetic${tick};\n`)); assert.equal(result.status, 0, result.stdout); });
test("rejects a quoted credential value from the Git index without leaking it", () => { const root = mkdtempSync(join(tmpdir(), "hospital-workspace-public-safety-index-quoted-")); try { const key = ["api", "key"].join("_"); const value = ["foo", apostrophe, "bar"].join(""); write(root, "fixture.json", `{${credential(key, value)}}\n`); spawnSync("git", ["init", "--quiet"], { cwd: root }); spawnSync("git", ["add", "fixture.json"], { cwd: root }); write(root, "fixture.json", "safe\n"); const result = run(root, "--git-index"); assertRule(result, "fixture.json", "CREDENTIAL_ASSIGNMENT_PATTERN"); assert.doesNotMatch(result.stdout, /foo/); } finally { rmSync(root, { recursive: true, force: true }); } });
for (const [format, content] of [["json", (value) => `{\"${escapedCredentialKey}\":\"${value}\"}\n`], ["yaml", (value) => `\"${escapedCredentialKey}\": \"${value}\"\n`], ["toml", (value) => `\"${escapedCredentialKey}\" = \"${value}\"\n`]]) test(`rejects Unicode-escaped credential key in ${format} without leaking its value`, () => { const result = fixture((root) => write(root, `escaped.${format}`, content("abcdefgh"))); assertRule(result, `escaped.${format}`, "CREDENTIAL_ASSIGNMENT_PATTERN"); assert.doesNotMatch(result.stdout, /abcdefgh/); });
for (const [format, key, content] of [["yaml", escapedKey("x61"), (value, name) => `\"${name}\": \"${value}\"\n`], ["yaml", escapedKey("U00000061"), (value, name) => `\"${name}\": \"${value}\"\n`], ["toml", escapedKey("U00000061"), (value, name) => `\"${name}\" = \"${value}\"\n`], ["js", escapedKey("x61"), (value, name) => `const config = { \"${name}\": \"${value}\" };\n`], ["ts", escapedKey("u{61}"), (value, name) => `const config = { \"${name}\": \"${value}\" };\n`]]) test(`rejects additional escaped credential key form in ${format} without leaking its value`, () => { const result = fixture((root) => write(root, `escaped-form.${format}`, content("abcdefgh", key))); assertRule(result, `escaped-form.${format}`, "CREDENTIAL_ASSIGNMENT_PATTERN"); assert.doesNotMatch(result.stdout, /abcdefgh/); });
test("allows escaped noncredential keys and empty or approved escaped credential values", () => { for (const [format, content] of [["json", `{\"${escapedNonCredentialKey}\":\"abcdefgh\",\"${escapedCredentialKey}\":\"\"}\n`], ["yaml", `\"${escapedNonCredentialKey}\": \"abcdefgh\"\n\"${escapedCredentialKey}\": \"example\"\n`], ["toml", `\"${escapedNonCredentialKey}\" = \"abcdefgh\"\n\"${escapedCredentialKey}\" = \"synthetic\"\n`]]) { const result = fixture((root) => write(root, `escaped.${format}`, content)); assert.equal(result.status, 0, result.stdout); } });
test("rejects typed TypeScript credential assignment without leaking its value", () => { const result = fixture((root) => write(root, "fixture.ts", `const ${["api", "Key"].join("")}: string = \"abcdefgh\";\n`)); assertRule(result, "fixture.ts", "CREDENTIAL_ASSIGNMENT_PATTERN"); assert.doesNotMatch(result.stdout, /abcdefgh/); });
test("rejects optional, definite, generic, multiline object, and function typed credential assignments", () => { const key = ["api", "Key"].join(""); const result = fixture((root) => write(root, "fixture.ts", `const ${key}?: string = \"abcdefgh\";\nconst ${key}!: string = \"abcdefgh\";\nconst ${key}: Record<string, \"x\"> = \"abcdefgh\";\nconst ${key}: {\n  value: string;\n} = \"abcdefgh\";\nconst ${key}: (value: string) => string = \"abcdefgh\";\n`)); assertRule(result, "fixture.ts", "CREDENTIAL_ASSIGNMENT_PATTERN"); assert.doesNotMatch(result.stdout, /abcdefgh/); });
test("accepts empty and exact sentinels for extended typed TypeScript syntax", () => { const key = ["api", "Key"].join(""); const token = ["auth", "Token"].join(""); const result = fixture((root) => write(root, "fixture.ts", `const ${key}?: Record<string, \"x\"> = \"\";\nconst ${key}!: { value: string } = \"example\";\nconst ${token}: (value: string) => string = \"synthetic\";\n`)); assert.equal(result.status, 0, result.stdout); });
test("rejects commented complex and multiline TypeScript credential initializers", () => { const key = ["api", "Key"].join(""); const token = ["auth", "Token"].join(""); const result = fixture((root) => write(root, "fixture.ts", `const ${key}: Record<\n  string,\n  /* synthetic ; = \"example\" */ { value: string }\n> = \"abcdefgh\";\nconst ${token}: (value: string // synthetic ; =\n) => string = \"abcdefgh\";\n`)); assertRule(result, "fixture.ts", "CREDENTIAL_ASSIGNMENT_PATTERN"); assert.doesNotMatch(result.stdout, /abcdefgh/); });
test("accepts commented complex TypeScript empty and approved credential sentinels", () => { const key = ["api", "Key"].join(""); const token = ["auth", "Token"].join(""); const result = fixture((root) => write(root, "fixture.ts", `const ${key}: Record<\n  string,\n  /* synthetic ; = */ { value: string }\n> = \"example\";\nconst ${token}: (value: string // synthetic ; =\n) => string = \"\";\n`)); assert.equal(result.status, 0, result.stdout); });
test("accepts typed TypeScript empty and approved sentinel assignments", () => { const result = fixture((root) => write(root, "fixture.ts", `const ${["api", "Key"].join("")}: string = \"example\";\nconst ${["auth", "Token"].join("")}: string = \"\";\n`)); assert.equal(result.status, 0, result.stdout); });
test("rejects tagged YAML, multiline TOML, and commented TypeScript credential assignments without leaking values", () => { const snake = ["api", "key"].join("_"); const token = ["auth", "token"].join("_"); const camel = ["api", "Key"].join(""); const basic = ["\"", "\"", "\""].join(""); const literal = ["'", "'", "'"].join(""); const result = fixture((root) => write(root, "fixture.ts", `${snake}: !!str \"abcdefgh\"\n${snake} = ${basic}abcdefgh${basic}\n${token} = ${literal}abcdefgh${literal}\nconst ${camel} /* synthetic */: string /* synthetic */ = \"abcdefgh\";\n`)); assertRule(result, "fixture.ts", "CREDENTIAL_ASSIGNMENT_PATTERN"); assert.doesNotMatch(result.stdout, /abcdefgh/); });
test("accepts empty and approved tagged YAML, multiline TOML, and commented TypeScript assignments", () => { const snake = ["api", "key"].join("_"); const token = ["auth", "token"].join("_"); const camel = ["api", "Key"].join(""); const basic = ["\"", "\"", "\""].join(""); const literal = ["'", "'", "'"].join(""); const result = fixture((root) => write(root, "fixture.ts", `${snake}: !!str \"example\"\n${snake} = ${basic}${basic}\n${token} = ${literal}synthetic${literal}\nconst ${camel} /* synthetic */: string /* synthetic */ = \"\";\n`)); assert.equal(result.status, 0, result.stdout); });
test("rejects custom, verbatim, anchored, and both-order combined YAML node-property credential assignments", () => { const snake = ["api", "key"].join("_"); const tag = ["!", "vault"].join(""); const verbatim = ["!<", "tag:example.invalid,2026:vault", ">"].join(""); const anchor = ["&", "fixture"].join(""); const result = fixture((root) => write(root, "fixture.yaml", `${snake}: ${tag} \"abcdefgh\"\n${snake}: ${verbatim} \"abcdefgh\"\n${snake}: ${anchor} \"abcdefgh\"\n${snake}: ${tag} ${anchor} \"abcdefgh\"\n${snake}: ${anchor} ${tag} \"abcdefgh\"\n${snake}: !!str &core \"abcdefgh\"\n${snake}: &reverse !!str \"abcdefgh\"\n`)); assertRule(result, "fixture.yaml", "CREDENTIAL_ASSIGNMENT_PATTERN"); assert.doesNotMatch(result.stdout, /abcdefgh/); });
test("accepts empty and approved YAML node-property credential sentinels", () => { const snake = ["api", "key"].join("_"); const token = ["auth", "token"].join("_"); const tag = ["!", "vault"].join(""); const verbatim = ["!<", "tag:example.invalid,2026:vault", ">"].join(""); const anchor = ["&", "fixture"].join(""); const result = fixture((root) => write(root, "fixture.yaml", `${snake}: ${tag} ${anchor} \"example\"\n${token}: ${anchor} ${verbatim} \"\"\n${snake}: &reverse !!str \"synthetic\"\n`)); assert.equal(result.status, 0, result.stdout); });
test("rejects credential aliases that resolve to anchored YAML scalar values", () => { const anchor = ["&", "secretref"].join(""); const snake = ["api", "key"].join("_"); const result = fixture((root) => write(root, "fixture.yaml", `memo: ${anchor} \"abcdefgh\"\n${snake}: *secretref\n`)); assertRule(result, "fixture.yaml", "CREDENTIAL_ASSIGNMENT_PATTERN"); assert.doesNotMatch(result.stdout, /abcdefgh/); });
test("accepts credential aliases that resolve to empty or approved anchored YAML scalars", () => { const snake = ["api", "key"].join("_"); const token = ["auth", "token"].join("_"); const result = fixture((root) => write(root, "fixture.yaml", `memo: &empty \"\"\n${snake}: *empty\nmemo: !vault &example \"example\"\n${token}: *example\n`)); assert.equal(result.status, 0, result.stdout); });
test("rejects credential aliases that resolve through anchored YAML alias chains", () => { const snake = ["api", "key"].join("_"); const result = fixture((root) => write(root, "fixture.yaml", `memo: &first \"abcdefgh\"\nbridge: &second *first\n${snake}: *second\n`)); assertRule(result, "fixture.yaml", "CREDENTIAL_ASSIGNMENT_PATTERN"); assert.doesNotMatch(result.stdout, /abcdefgh/); });
test("accepts empty and approved credential aliases through YAML alias chains", () => { const snake = ["api", "key"].join("_"); const token = ["auth", "token"].join("_"); const result = fixture((root) => write(root, "fixture.yaml", `memo: &first \"example\"\nbridge: &second *first\n${token}: *second\nmemo: &blank \"\"\nbridge: &alsoBlank *blank\n${snake}: *alsoBlank\n`)); assert.equal(result.status, 0, result.stdout); });
test("rejects credential aliases from the Git index without leaking anchored values", () => { const root = mkdtempSync(join(tmpdir(), "hospital-workspace-public-safety-index-yaml-alias-")); try { const snake = ["api", "key"].join("_"); write(root, "fixture.yaml", `memo: &secretref \"abcdefgh\"\n${snake}: *secretref\n`); spawnSync("git", ["init", "--quiet"], { cwd: root }); spawnSync("git", ["add", "fixture.yaml"], { cwd: root }); write(root, "fixture.yaml", "safe\n"); const result = run(root, "--git-index"); assertRule(result, "fixture.yaml", "CREDENTIAL_ASSIGNMENT_PATTERN"); assert.doesNotMatch(result.stdout, /abcdefgh/); } finally { rmSync(root, { recursive: true, force: true }); } });
for (const [name, tag] of [["non-specific", "!"], ["core", "!!str"], ["dot", ["!", "foo.bar"].join("")], ["percent", ["!", "foo%20bar"].join("")], ["URI characters", ["!", "foo:bar+baz@site;part?x=y"].join("")], ["verbatim", ["!<", "tag:example.invalid,2026:vault", ">"].join("")]]) test(`rejects tagged YAML credential assignment: ${name}`, () => { const snake = ["api", "key"].join("_"); const result = fixture((root) => write(root, "fixture.yaml", `${snake}: ${tag} \"abcdefgh\"\n`)); assertRule(result, "fixture.yaml", "CREDENTIAL_ASSIGNMENT_PATTERN"); assert.doesNotMatch(result.stdout, /abcdefgh/); });
test("accepts empty and approved sentinels behind URI-style YAML tags", () => { const snake = ["api", "key"].join("_"); const token = ["auth", "token"].join("_"); const result = fixture((root) => write(root, "fixture.yaml", `${snake}: !foo.bar \"example\"\n${token}: !foo%20bar \"\"\n`)); assert.equal(result.status, 0, result.stdout); });
test("recognizes punctuation-bearing YAML tag suffixes including hash", () => { const snake = ["api", "key"].join("_"); const tags = ["$", "&", "'", "(", ")", "*", "~"].map((character) => ["!foo", character, "bar"].join("")); const result = fixture((root) => write(root, "fixture.yaml", `${tags.map((tag) => `${snake}: ${tag} \"abcdefgh\"`).join("\n")}\n${snake}: !foo#bar \"abcdefgh\"\n`)); assertRule(result, "fixture.yaml", "CREDENTIAL_ASSIGNMENT_PATTERN"); assert.doesNotMatch(result.stdout, /abcdefgh/); });
test("accepts empty and approved sentinels behind punctuation-bearing YAML tags", () => { const snake = ["api", "key"].join("_"); const token = ["auth", "token"].join("_"); const result = fixture((root) => write(root, "fixture.yaml", `${snake}: !foo$bar \"example\"\n${token}: !foo&bar \"\"\n`)); assert.equal(result.status, 0, result.stdout); });
test("rejects URI-style YAML tag credentials from the Git index without leaking the value", () => { const root = mkdtempSync(join(tmpdir(), "hospital-workspace-public-safety-index-yaml-tag-")); try { const snake = ["api", "key"].join("_"); const tag = ["!", "foo%20bar"].join(""); write(root, "fixture.yaml", `${snake}: ${tag} \"abcdefgh\"\n`); spawnSync("git", ["init", "--quiet"], { cwd: root }); spawnSync("git", ["add", "fixture.yaml"], { cwd: root }); write(root, "fixture.yaml", "safe\n"); const result = run(root, "--git-index"); assertRule(result, "fixture.yaml", "CREDENTIAL_ASSIGNMENT_PATTERN"); assert.doesNotMatch(result.stdout, /abcdefgh/); } finally { rmSync(root, { recursive: true, force: true }); } });
for (const [format, make] of formats) test(`rejects quoted credential assignment in ${format}`, () => { const result = fixture((root) => write(root, `fixture.${format}`, make(["client", "secret"].join("_")))); assertRule(result, `fixture.${format}`, "CREDENTIAL_ASSIGNMENT_PATTERN"); assert.doesNotMatch(result.stdout, /abcdefgh/); });
for (const key of ["apiKey", "api-key", "apikey", "access_token", "refresh_token", "auth_token", "password", "passwd", "secret", "private_key", "signing_key", "cookie_secret", "jwt_secret"]) test(`rejects credential key ${key}`, () => { const result = fixture((root) => write(root, "fixture.txt", `${key}=\"abcdefgh\"\n`)); assertRule(result, "fixture.txt", "CREDENTIAL_ASSIGNMENT_PATTERN"); });
test("fails closed on invalid UTF-8 in a worktree blob", () => { const result = fixture((root) => write(root, "fixture.txt", Buffer.from([0xc3, 0x28]))); assertRule(result, "fixture.txt", "INVALID_UTF8"); });
for (const value of internalIpv6) test("rejects internal IPv6 on the worktree surface without leaking the value", () => { const result = fixture((root) => write(root, "network.txt", `${value}\n`)); assertRule(result, "network.txt", "PROHIBITED_INTERNAL_NETWORK_REFERENCE"); assert.doesNotMatch(result.stdout, /fd12|fdff|fe80/i); });
test("accepts IPv6 values immediately outside internal ranges and public documentation addresses", () => { const result = fixture((root) => write(root, "network.txt", [ipv6("FBFF", "", "1"), ipv6("FEC0", "", "1"), ipv6("2001", "db8", "", "1"), ipv6("2001", "4860", "4860", "", "8888")].join("\n"))); assert.equal(result.status, 0, result.stdout); });
test("rejects internal IPv6 from the Git index even when the worktree is safe", () => { const root = mkdtempSync(join(tmpdir(), "hospital-workspace-public-safety-index-ipv6-")); try { write(root, "network.txt", `${internalIpv6[2]}\n`); spawnSync("git", ["init", "--quiet"], { cwd: root }); spawnSync("git", ["add", "network.txt"], { cwd: root }); write(root, "network.txt", "safe\n"); const result = run(root, "--git-index"); assertRule(result, "network.txt", "PROHIBITED_INTERNAL_NETWORK_REFERENCE"); assert.doesNotMatch(result.stdout, /fe80/i); } finally { rmSync(root, { recursive: true, force: true }); } });
for (const [path, payload, rule] of [
  ["node_modules/fixture/invalid.bin", Buffer.from([0xc3, 0x28]), "INVALID_UTF8"],
  [".pnpm/fixture/invalid.bin", Buffer.from([0xc3, 0x28]), "INVALID_UTF8"],
  ["node_modules/fixture/control.bin", Buffer.from([0x61, 0x00, 0x62]), "BINARY_BLOB_UNAPPROVED"],
  [".pnpm/fixture/control.bin", Buffer.from([0x61, 0x1f, 0x62]), "BINARY_BLOB_UNAPPROVED"],
  ["node_modules/fixture/credential.txt", `{${credential(["api", "key"].join("_"))}}\n`, "CREDENTIAL_ASSIGNMENT_PATTERN"],
  [".pnpm/fixture/credential.txt", `{${credential(["api", "key"].join("_"))}}\n`, "CREDENTIAL_ASSIGNMENT_PATTERN"]
]) test(`scans prohibited worktree content under ${path.split("/")[0]}`, () => { const result = fixture((root) => write(root, path, payload)); assertRule(result, path, rule); assert.doesNotMatch(result.stdout, /abcdefgh|ab/); });
test("scans nested .git-named content instead of treating it as repository metadata", () => { const path = ["fixture", ".git", "credential.txt"].join("/"); const result = fixture((root) => write(root, path, `{${credential(["api", "key"].join("_"))}}\n`)); assertRule(result, path, "CREDENTIAL_ASSIGNMENT_PATTERN"); });
test("fails closed on invalid UTF-8 in a staged blob", () => { const root = mkdtempSync(join(tmpdir(), "hospital-workspace-public-safety-index-utf8-")); try { write(root, "fixture.bin", Buffer.from([0xc3, 0x28])); spawnSync("git", ["init", "--quiet"], { cwd: root }); spawnSync("git", ["add", "fixture.bin"], { cwd: root }); const result = run(root, "--git-index"); assertRule(result, "fixture.bin", "INVALID_UTF8"); } finally { rmSync(root, { recursive: true, force: true }); } });
for (const [mode, path] of [["120000", "public-link"], ["160000", "public-gitlink"]]) test(`rejects special Git-index mode ${mode} without reading its target`, () => { const root = mkdtempSync(join(tmpdir(), "hospital-workspace-public-safety-index-mode-")); try { const target = ["config", "private", "runtime.env"].join("/"); indexCacheInfo(root, mode, path, target); const result = run(root, "--git-index"); assertRule(result, path, "UNSUPPORTED_GIT_INDEX_MODE"); assert.doesNotMatch(result.stdout, /runtime\.env|config\/private/); } finally { rmSync(root, { recursive: true, force: true }); } });
test("accepts a regular executable Git-index blob", () => { const root = mkdtempSync(join(tmpdir(), "hospital-workspace-public-safety-index-executable-")); try { indexCacheInfo(root, "100755", "fixture.sh", "echo safe\n"); const result = run(root, "--git-index"); assert.equal(result.status, 0, result.stdout); } finally { rmSync(root, { recursive: true, force: true }); } });
for (const [name, payload] of [["nul", Buffer.from([0x61, 0x00, 0x62])], ["control", Buffer.from([0x61, 0x1f, 0x62])], ["del", Buffer.from([0x61, 0x7f, 0x62])]]) test(`fails closed on valid UTF-8 ${name} control bytes in a worktree blob`, () => { const result = fixture((root) => write(root, "fixture.bin", payload)); assertRule(result, "fixture.bin", "BINARY_BLOB_UNAPPROVED"); assert.doesNotMatch(result.stdout, /ab/); });
for (const [name, payload] of [["nul", Buffer.from([0x61, 0x00, 0x62])], ["control", Buffer.from([0x61, 0x1f, 0x62])]]) test(`fails closed on valid UTF-8 ${name} control bytes in an index blob`, () => { const root = mkdtempSync(join(tmpdir(), "hospital-workspace-public-safety-index-control-")); try { write(root, "fixture.bin", payload); spawnSync("git", ["init", "--quiet"], { cwd: root }); spawnSync("git", ["add", "fixture.bin"], { cwd: root }); write(root, "fixture.bin", "safe\n"); const result = run(root, "--git-index"); assertRule(result, "fixture.bin", "BINARY_BLOB_UNAPPROVED"); assert.doesNotMatch(result.stdout, /ab/); } finally { rmSync(root, { recursive: true, force: true }); } });
test("global failures use stable path and rule identifiers without raw system errors", () => { const missing = join(tmpdir(), ["hospital", "workspace", "missing", "root"].join("-")); const result = run(missing, "--worktree"); assert.notEqual(result.status, 0, result.stdout); const report = JSON.parse(result.stdout); assert.deepEqual(report.findings, [{ path: "__public_safety__", rule: "PUBLIC_SAFETY_CHECK_ERROR" }]); assert.doesNotMatch(result.stdout, /ENOENT|missing-root|no such file/i); });
test("--git-index reads the staged blob, not a changed worktree", () => { const root = mkdtempSync(join(tmpdir(), "hospital-workspace-public-safety-index-")); try { write(root, "fixture.txt", "safe\n"); spawnSync("git", ["init", "--quiet"], { cwd: root }); spawnSync("git", ["config", "user.email", "fixture@example.invalid"], { cwd: root }); spawnSync("git", ["config", "user.name", "Fixture"], { cwd: root }); spawnSync("git", ["add", "fixture.txt"], { cwd: root }); write(root, "fixture.txt", `{${credential(["api", "key"].join("_"))}}\n`); const result = run(root, "--git-index"); assert.equal(result.status, 0, result.stdout); } finally { rmSync(root, { recursive: true, force: true }); } });
test("--git-index rejects a prohibited staged UTF-8 blob even when worktree is safe", () => { const root = mkdtempSync(join(tmpdir(), "hospital-workspace-public-safety-index-reject-")); try { write(root, "fixture.txt", `{${credential(["api", "key"].join("_"))}}\n`); spawnSync("git", ["init", "--quiet"], { cwd: root }); spawnSync("git", ["config", "user.email", "fixture@example.invalid"], { cwd: root }); spawnSync("git", ["config", "user.name", "Fixture"], { cwd: root }); spawnSync("git", ["add", "fixture.txt"], { cwd: root }); write(root, "fixture.txt", "safe\n"); const result = run(root, "--git-index"); assertRule(result, "fixture.txt", "CREDENTIAL_ASSIGNMENT_PATTERN"); assert.doesNotMatch(result.stdout, /abcdefgh/); } finally { rmSync(root, { recursive: true, force: true }); } });
for (const [path, content, rule, sibling] of [
  [".env", "SAFE=true\n", "TRACKED_ENV_FILE"],
  ["config/private/runtime.json", "{}\n", "TRACKED_PRIVATE_RUNTIME_CONFIG"],
  ["dist/app.js", "x\n", "TRACKED_BUILD_OUTPUT"],
  ["backup/dump.sql", "x\n", "TRACKED_DATABASE_DUMP_OR_BACKUP"],
  ["keys/example.pem", `${privateKeyMarker}\n`, "TRACKED_CERTIFICATE_OR_PRIVATE_KEY"],
  ["docs/network.md", `${privateNetwork}\n`, "PROHIBITED_INTERNAL_NETWORK_REFERENCE"],
  ["yarn.lock", "# second lock\n", "SECOND_JAVASCRIPT_LOCKFILE"],
  ["logs/run.log", "synthetic log\n", "TRACKED_LOG"],
  ["scripts/phase-01-old.mjs", "export default {};\n", "LEGACY_PHASE_SCRIPT"],
  ["legacy/copied.ts", "export const copied = true;\n", "UNREGISTERED_LEGACY_COPY"],
  ["src/generated.js", "export const generated = true;\n", "GENERATED_SOURCE_BESIDE_TYPESCRIPT", "src/generated.ts"],
  ["docs/portal.md", `Dependency: ${portalAlias}\n`, "LEGACY_PORTAL_ALIAS"],
  ["scripts/migration/example.mjs", `export const marker = \"${legacyCopyMarker}\";\n`, "UNREGISTERED_LEGACY_COPY"]
]) test(`rejects ${path}`, () => { const result = fixture((root) => { write(root, path, content); if (sibling) write(root, sibling, "export const source = true;\n"); }); assertRule(result, path, rule); });
test("rejects PGP private-key armor without leaking its header", () => { const result = fixture((root) => write(root, "fixture.asc", `${pgpPrivateKeyMarker}\n`)); assertRule(result, "fixture.asc", "PRIVATE_KEY_MARKER"); assert.doesNotMatch(result.stdout, /PGP PRIVATE KEY/); });
