import assert from "node:assert/strict";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { spawn, spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import test from "node:test";

const scriptDirectory = dirname(fileURLToPath(import.meta.url)); const checker = resolve(scriptDirectory, "check-evidence-manifest.mjs"); const schema = resolve(scriptDirectory, "../../docs/program/templates/EVIDENCE-MANIFEST.schema.json"); const source = "a".repeat(40); const result = "b".repeat(40); const tree = "c".repeat(64); const ref = "ci://run/fixture";
const EVIDENCE_CHECKER_HOST_CONTROL_KEYS = [
  "CI", "GITHUB_ACTIONS", "GITHUB_SHA", "GITHUB_REF", "GITHUB_REF_NAME", "GITHUB_HEAD_REF", "GITHUB_BASE_REF", "GITHUB_EVENT_NAME", "GITHUB_EVENT_PATH", "GITHUB_RUN_ID", "GITHUB_RUN_ATTEMPT", "GITHUB_WORKSPACE", "RUNNER_TEMP", "RUNNER_WORKSPACE",
  "HW_CI_COMMIT_SHA", "HW_CI_RUN_ID", "HW_CI_RUN_ATTEMPT", "HW_CI_BASE_SHA", "HW_CI_HEAD_SHA", "HW_CI_EVENT_NAME", "HW_CI_REHEARSAL_EXPECTED", "HW_CI_RECOVERY_EXPECTED",
  "HW_EVIDENCE_MANIFEST", "HW_EVIDENCE_SCHEMA", "HW_EVIDENCE_EXPECTED_SOURCE_COMMIT", "HW_EVIDENCE_EXPECTED_RESULT_COMMIT", "HW_EVIDENCE_EXPECTED_RESULT_TREE", "HW_EVIDENCE_EXPECTED_ROLLBACK_REHEARSAL", "HW_EVIDENCE_EXPECTED_RECOVERY_REHEARSAL",
  "GIT_DIR", "GIT_WORK_TREE", "GIT_INDEX_FILE", "GIT_COMMON_DIR", "GIT_OBJECT_DIRECTORY", "GIT_ALTERNATE_OBJECT_DIRECTORIES", "GIT_CEILING_DIRECTORIES"
];
const EVIDENCE_CHECKER_RUNTIME_KEYS = ["PATH", "Path", "SystemRoot", "SYSTEMROOT", "ComSpec", "COMSPEC", "PATHEXT", "HOME", "USERPROFILE", "HOMEDRIVE", "HOMEPATH", "TEMP", "TMP", "TMPDIR", "LOCALAPPDATA", "APPDATA", "PROGRAMDATA", "ProgramFiles", "ProgramFiles(x86)", "ProgramW6432", "WINDIR", "LANG", "LC_ALL", "LC_CTYPE", "TERM", "COLORTERM", "NO_COLOR", "TZ"];
const EVIDENCE_CHECKER_OVERRIDE_KEYS = new Set(EVIDENCE_CHECKER_HOST_CONTROL_KEYS);
const UNRELATED_CI_FINDINGS = ["TRUSTED_BINDING_REQUIRED", "TRUSTED_REHEARSAL_EXPECTATION_REQUIRED"];
function buildEvidenceCheckerTestEnvironment({ mode, overrides = {}, hostEnvironment = process.env }) {
  assert.ok(mode === "LOCAL" || mode === "CI", `unsupported Evidence checker test mode: ${mode}`);
  const copiedHostEnvironment = { ...hostEnvironment };
  for (const key of EVIDENCE_CHECKER_HOST_CONTROL_KEYS) delete copiedHostEnvironment[key];
  const environment = {};
  for (const key of EVIDENCE_CHECKER_RUNTIME_KEYS) if (Object.hasOwn(copiedHostEnvironment, key)) environment[key] = copiedHostEnvironment[key];
  for (const [key, value] of Object.entries(overrides)) { assert.ok(EVIDENCE_CHECKER_OVERRIDE_KEYS.has(key), `unauthorized Evidence checker environment override: ${key}`); assert.equal(typeof value, "string"); environment[key] = value; }
  if (mode === "LOCAL") { assert.equal(environment.CI, undefined); assert.equal(environment.GITHUB_ACTIONS, undefined); for (const key of Object.keys(environment)) assert.ok(!key.startsWith("HW_CI_"), key); }
  else { assert.equal(environment.CI, "true"); assert.equal(environment.GITHUB_ACTIONS, "true"); for (const key of ["HW_CI_COMMIT_SHA", "HW_CI_RUN_ID", "HW_CI_RUN_ATTEMPT"]) assert.ok(environment[key], `missing explicit CI test binding: ${key}`); }
  return environment;
}
function syntheticCiOverrides(commit = source) { return { CI: "true", GITHUB_ACTIONS: "true", HW_CI_COMMIT_SHA: commit, HW_CI_RUN_ID: "9001", HW_CI_RUN_ATTEMPT: "1" }; }
const privacy = Object.fromEntries(["patientData", "employeePersonData", "identityNumbers", "diagnosisClinicalText", "phone", "email", "detailedFee", "cookie", "token", "password", "apiKeyClientSecret", "privateKeySigningMaterial", "internalHostnameNetwork", "clinicalPromptContent"].map((key) => [key, "CLEAR"]));
test("rejects labeled formatted phones, currency fees, and scheme-agnostic Authorization credentials without leakage", () => { const values = [["patient：Alice", /patient|Alice/i], ["phone: (202) 555-0173", /202|555|0173|phone/i], ["mobile: 202.555.0173", /202|555|0173|mobile/i], ["phone: +1 (202) 555-0173", /202|555|0173|phone/i], ["phone: 202/555/0173", /202|555|0173|phone/i], ["phone：202-555-0173", /202|555|0173|phone/i], ["phone: 202–555–0173", /202|555|0173|phone/i], ["phone: 202‑555‑0173", /202|555|0173|phone/i], ["phone: 202 555 0173", /202|555|0173|phone/i], ["amount: $123.45", /amount|123\.45/i], ["amount: $1,234.56", /amount|1,234\.56/i], ["amount：₹1,234.56", /amount|1,234\.56/i], ["detailed_fee: ￥123.45", /detailed_fee|123\.45/i], ["fee_amount: ¥123.45", /fee_amount|123\.45/i], ["detailed_fee: €1,234.56", /detailed_fee|1,234\.56/i], ["Authorization: Token opaque-fixture", /Authorization|Token|opaque-fixture/i], ["Authorization: Digest opaque-fixture", /Authorization|Digest|opaque-fixture/i], ["Authorization：Token opaque-fixture", /Authorization|Token|opaque-fixture/i]]; for (const [value, redacted] of values) { const output = runLocal(base({ limitations: [value] })); assertFailure(output, "PROHIBITED_PRIVACY_CONTENT", { exactRules: ["PROHIBITED_PRIVACY_CONTENT"] }); assert.doesNotMatch(output.stdout, redacted); } });
const REVIEW_AGENT_MODELS = { terra_reviewer: "gpt-5.6-terra", terra_security: "gpt-5.6-terra", sol_acceptance: "gpt-5.6-sol", sol_architecture_security: "gpt-5.6-sol", sol_phase_gate: "gpt-5.6-sol" };
function configuredAgentModel(path) { const text = readFileSync(path, "utf8"); const match = text.match(/^model\s*=\s*"([^"]+)"\s*$/m); assert.ok(match, `missing model in ${path}`); return match[1]; }
function checkerAgentModel(agent) { const text = readFileSync(checker, "utf8"); const section = text.match(/const AGENT_MODEL = new Map\(\[(.*?)\]\);/s)?.[1] ?? ""; const match = section.match(new RegExp(`\\[\\"${agent}\\",\\s*\\"([^\\"]+)\\"\\]`)); assert.ok(match, `missing checker model for ${agent}`); return match[1]; }
test("review model mapping matches checker entries and every authoritative reviewer-agent TOML", () => { for (const [agent, model] of Object.entries(REVIEW_AGENT_MODELS)) { const path = resolve(process.cwd(), `.codex/agents/${agent}.toml`); assert.equal(configuredAgentModel(path), model, agent); assert.equal(checkerAgentModel(agent), model, agent); } });
test("receipt helper uses the configured model family for Terra and Sol fixtures", () => { for (const [agent, model] of Object.entries(REVIEW_AGENT_MODELS)) assert.equal(receipt(agent).model, model); });
test("[LOCAL] permits ordinary Authorization prose without an assignment separator", () => { for (const value of ["Authorization Bearer tokens require redaction.", "Authorization　Bearer tokens require redaction."]) assertPass(runLocal(base({ limitations: [value] }))); });
test("[LOCAL] permits a labeled under-length phone fragment", () => { assertPass(runLocal(base({ limitations: ["phone: 202/555"] }))); });
const ipv6 = (...parts) => parts.join(":"); const internalIpv6 = [ipv6("FD12", "3456", "789A", "", "1"), ["[", ipv6("fE80", "", "1%Ethernet"), "]"].join(""), ipv6("FC00", ""), ipv6("FdFf", "FfFf", "FfFf", "FfFf", "FfFf", "FfFf", "FfFf", "FfFf"), ipv6("FE80", ""), ipv6("fEbF", "FfFf", "FfFf", "FfFf", "FfFf", "FfFf", "FfFf", "FfFf"), `${ipv6("FC00", "")}/7`, `${ipv6("Fe80", "")}/10`];
function receipt(agent = "terra_reviewer", outcome = "APPROVED", overrides = {}) { return { schemaVersion: "hospital-workspace.review-receipt.v1", reviewerRole: "independent-reviewer", agent, model: REVIEW_AGENT_MODELS[agent] ?? "gpt-5.6-terra", reviewType: "implementation", sourceCommit: source, resultCommit: result, resultTree: tree, reviewedDiffBase: source, reviewedDiffHead: result, outcome, limitations: ["Synthetic fixture."], reference: "external://review/fixture", ...overrides }; }
function evidence(status = "NOT_APPLICABLE") { return { status, reference: status === "PASS" ? ref : "not-run://fixture", rationale: "Synthetic fixture.", applicabilityBoundary: "No production system.", reviewerConfirmation: "Confirmed." }; }
function base(overrides = {}) { return { schemaVersion: "hospital-workspace.evidence.v3", program: "hospital-workspace", scope: { kind: "task", phaseId: "HW-00", taskId: "HW00-06" }, risk: "medium", acceptanceTier: "terra", sourceBinding: { kind: "commit", value: source }, resultBinding: { kind: "tree", value: tree }, resultCommit: result, branch: "hw/hw-00/hw00-06-ci-evidence-framework", environments: [{ id: "ubuntu-ci", required: true, status: "PASS", claims: ["ubuntu-ci"], evidenceRefs: [ref] }], requiredCheckIds: ["foundation-checks"], checks: [{ id: "foundation-checks", required: true, environment: "ubuntu-ci", status: "PASS", evidenceRef: ref }], ciArtifacts: [{ name: "report.json", reference: ref, binding: { kind: "tree", value: tree } }], negativeScenarios: [{ id: "negative", status: "PASS", evidenceRef: ref }], rollback: evidence(), recovery: evidence(), rehearsalRequirements: { rollback: false, recovery: false }, requiredReviewAgents: [{ agent: "terra_reviewer", outcome: "APPROVED" }], reviewReceipts: [receipt()], privacyCategories: privacy, dataClassification: "public-synthetic", limitations: ["Synthetic fixture."], decision: "PASS", decisionOwner: "parent_codex", decidedAt: "2026-08-31T00:00:00Z", ...overrides }; }
function checkerEnvironment(options = {}) { return buildEvidenceCheckerTestEnvironment({ mode: options.mode ?? "LOCAL", overrides: options.overrides ?? {}, hostEnvironment: options.hostEnvironment ?? process.env }); }
function run(value, args = [], cwd = null, options = {}) { const root = mkdtempSync(join(tmpdir(), "hospital-workspace-evidence-")); const path = join(root, "manifest.json"); writeFileSync(path, `${JSON.stringify(value)}\n`); try { return spawnSync(process.execPath, [checker, "--schema", schema, "--manifest", path, ...args], { cwd: cwd ?? root, encoding: "utf8", env: checkerEnvironment(options) }); } finally { rmSync(root, { recursive: true, force: true }); } }
function runSchemaVariant(value, mutateSchema) { const root = mkdtempSync(join(tmpdir(), "hospital-workspace-evidence-schema-")); const manifestPath = join(root, "manifest.json"); const schemaPath = join(root, "schema.json"); const schemaCopy = JSON.parse(readFileSync(schema, "utf8")); mutateSchema(schemaCopy); writeFileSync(manifestPath, `${JSON.stringify(value)}\n`); writeFileSync(schemaPath, `${JSON.stringify(schemaCopy)}\n`); try { return spawnSync(process.execPath, [checker, "--schema", schemaPath, "--manifest", manifestPath], { cwd: root, encoding: "utf8", env: checkerEnvironment({ mode: "LOCAL" }) }); } finally { rmSync(root, { recursive: true, force: true }); } }
function runLocal(value, args = [], cwd = null, overrides = {}, hostEnvironment = process.env) { return run(value, args, cwd, { mode: "LOCAL", overrides, hostEnvironment }); }
function runCi(value, args = [], cwd = null, overrides = syntheticCiOverrides(), hostEnvironment = process.env) { return run(value, args, cwd, { mode: "CI", overrides, hostEnvironment }); }
function runCanonical(args = [], options = {}) { return spawnSync(process.execPath, [checker, "--template", ...args], { cwd: process.cwd(), encoding: "utf8", env: checkerEnvironment(options) }); }
function runAsync(value, args = [], cwd = null, options = {}) { const root = mkdtempSync(join(tmpdir(), "hospital-workspace-evidence-async-")); const path = join(root, "manifest.json"); writeFileSync(path, `${JSON.stringify(value)}\n`); return new Promise((resolveRun, rejectRun) => { const child = spawn(process.execPath, [checker, "--schema", schema, "--manifest", path, ...args], { cwd: cwd ?? root, env: checkerEnvironment(options) }); let stdout = ""; let stderr = ""; child.stdout.setEncoding("utf8"); child.stderr.setEncoding("utf8"); child.stdout.on("data", (chunk) => { stdout += chunk; }); child.stderr.on("data", (chunk) => { stderr += chunk; }); child.once("error", (error) => { rmSync(root, { recursive: true, force: true }); rejectRun(error); }); child.once("close", (status) => { rmSync(root, { recursive: true, force: true }); resolveRun({ status, stdout, stderr }); }); }); }
function report(output) { assert.equal(output.error, undefined, output.error?.message); let parsed; try { parsed = JSON.parse(output.stdout); } catch { assert.fail(`checker output is not JSON: ${output.stdout}`); } assert.ok(Array.isArray(parsed.findings), output.stdout); return parsed; }
function assertPass(output) { assert.equal(output.status, 0, `${output.stdout}${output.stderr ?? ""}`); const parsed = report(output); assert.equal(parsed.status, "PASS", output.stdout); assert.deepEqual(parsed.findings, [], output.stdout); return parsed; }
function assertFailure(output, expectedRules, { exactRules = null, permitCiFindings = false } = {}) { assert.notEqual(output.status, 0, output.stdout); const parsed = report(output); assert.equal(parsed.status, "FAIL", output.stdout); const rules = parsed.findings.map((finding) => finding.rule); const expected = Array.isArray(expectedRules) ? expectedRules : [expectedRules]; for (const expectedRule of expected) { if (expectedRule instanceof RegExp) assert.ok(rules.some((rule) => expectedRule.test(rule)), `${expectedRule}: ${output.stdout}`); else assert.ok(rules.includes(expectedRule), `${expectedRule}: ${output.stdout}`); } if (!permitCiFindings) for (const rule of UNRELATED_CI_FINDINGS) assert.ok(!rules.includes(rule), `unrelated ${rule}: ${output.stdout}`); if (exactRules) assert.deepEqual([...new Set(rules)].sort(), [...new Set(exactRules)].sort(), output.stdout); return parsed; }
function git(root, args) { const output = spawnSync("git", args, { cwd: root, encoding: "utf8" }); assert.equal(output.status, 0, output.stderr); return output.stdout.trim(); }
function boundRepository() { const root = mkdtempSync(join(tmpdir(), "hospital-workspace-evidence-git-")); git(root, ["init", "--quiet"]); git(root, ["config", "user.email", "fixture@example.invalid"]); git(root, ["config", "user.name", "Fixture"]); writeFileSync(join(root, "fixture.txt"), "source\n"); git(root, ["add", "fixture.txt"]); git(root, ["commit", "--quiet", "-m", "source"]); const sourceCommit = git(root, ["rev-parse", "HEAD"]); const sourceTree = git(root, ["rev-parse", "HEAD^{tree}"]); writeFileSync(join(root, "fixture.txt"), "result\n"); git(root, ["add", "fixture.txt"]); git(root, ["commit", "--quiet", "-m", "result"]); return { root, sourceCommit, sourceTree, resultCommit: git(root, ["rev-parse", "HEAD"]), resultTree: git(root, ["rev-parse", "HEAD^{tree}"]) }; }
function withBindings(bindings, overrides = {}) { const review = receipt("terra_reviewer", "APPROVED", { sourceCommit: bindings.sourceCommit, resultCommit: bindings.resultCommit, resultTree: bindings.resultTree, reviewedDiffBase: bindings.sourceCommit, reviewedDiffHead: bindings.resultCommit }); return base({ sourceBinding: { kind: "commit", value: bindings.sourceCommit }, resultBinding: { kind: "tree", value: bindings.resultTree }, resultCommit: bindings.resultCommit, reviewReceipts: [review], ciArtifacts: [{ name: "report.json", reference: ref, binding: { kind: "tree", value: bindings.resultTree } }], ...overrides }); }
test("[LOCAL] accepts a valid low-risk external Terra receipt and [CI] accepts a valid medium-risk CI receipt", () => { assertPass(runLocal(base({ risk: "low", ciArtifacts: [] }))); const repository = boundRepository(); try { const args = ["--expected-source-commit", repository.sourceCommit, "--expected-result-commit", repository.resultCommit, "--expected-result-tree", repository.resultTree, "--expected-rollback-rehearsal", "not-required", "--expected-recovery-rehearsal", "not-required"]; assertPass(runCi(withBindings(repository), args, repository.root, syntheticCiOverrides(repository.resultCommit))); } finally { rmSync(repository.root, { recursive: true, force: true }); } });
test("canonical template validation passes locally and in an explicit CI host only without custom inputs", () => { assertPass(runCanonical([], { mode: "LOCAL" })); assertPass(runCanonical([], { mode: "CI", overrides: syntheticCiOverrides() })); });
test("template mode rejects custom manifest/schema, CI flag, and trusted inputs", () => { assertFailure(runLocal(base(), ["--template"]), "EVIDENCE_MANIFEST_CHECK_ERROR", { exactRules: ["EVIDENCE_MANIFEST_CHECK_ERROR"] }); for (const args of [["--ci"], ["--schema", schema], ["--expected-source-commit", source], ["--expected-rollback-rehearsal", "not-required"], ["--expected-recovery-rehearsal", "not-required"]]) assertFailure(runCanonical(args, { mode: "LOCAL" }), "EVIDENCE_MANIFEST_CHECK_ERROR", { exactRules: ["EVIDENCE_MANIFEST_CHECK_ERROR"] }); });
test("[CI] a real manifest cannot bypass trusted inputs without template mode", () => { const output = runCi(base()); assertFailure(output, ["TRUSTED_BINDING_REQUIRED", "TRUSTED_REHEARSAL_EXPECTATION_REQUIRED"], { exactRules: ["TRUSTED_BINDING_REQUIRED", "TRUSTED_REHEARSAL_EXPECTATION_REQUIRED"], permitCiFindings: true }); });
test("[LOCAL] accepts high-risk PASS with rollback and recovery", () => { const sol = receipt("sol_acceptance", "ACCEPT"); assertPass(runLocal(base({ risk: "high", acceptanceTier: "sol-acceptance", rollback: evidence("PASS"), recovery: evidence("PASS"), requiredReviewAgents: [{ agent: "terra_reviewer", outcome: "APPROVED" }, { agent: "sol_acceptance", outcome: "ACCEPT" }], reviewReceipts: [receipt(), sol] }))); });
test("[LOCAL] a non-template manifest in a Git repository validates actual objects without trusted flags", () => { const repository = boundRepository(); try { const missing = runLocal(base(), [], repository.root); assertFailure(missing, ["SOURCE_GIT_OBJECT_MISSING", "RESULT_COMMIT_GIT_OBJECT_MISSING", "RESULT_TREE_GIT_OBJECT_MISSING"], { exactRules: ["SOURCE_GIT_OBJECT_MISSING", "RESULT_COMMIT_GIT_OBJECT_MISSING", "RESULT_TREE_GIT_OBJECT_MISSING"] }); assertPass(runLocal(withBindings(repository), [], repository.root)); } finally { rmSync(repository.root, { recursive: true, force: true }); } });
test("[LOCAL] Git-reported bare and explicit inherited Git-directory contexts validate actual objects", () => { const repository = boundRepository(); const bare = mkdtempSync(join(tmpdir(), "hospital-workspace-evidence-bare-")); const context = mkdtempSync(join(tmpdir(), "hospital-workspace-evidence-context-")); try { git(bare, ["init", "--bare", "--quiet"]); let output = runLocal(base(), [], bare); assertFailure(output, ["SOURCE_GIT_OBJECT_MISSING", "RESULT_COMMIT_GIT_OBJECT_MISSING", "RESULT_TREE_GIT_OBJECT_MISSING"], { exactRules: ["SOURCE_GIT_OBJECT_MISSING", "RESULT_COMMIT_GIT_OBJECT_MISSING", "RESULT_TREE_GIT_OBJECT_MISSING"] }); const overrides = { GIT_DIR: join(repository.root, ".git"), GIT_WORK_TREE: repository.root }; output = runLocal(base(), [], context, overrides); assertFailure(output, ["SOURCE_GIT_OBJECT_MISSING", "RESULT_COMMIT_GIT_OBJECT_MISSING", "RESULT_TREE_GIT_OBJECT_MISSING"], { exactRules: ["SOURCE_GIT_OBJECT_MISSING", "RESULT_COMMIT_GIT_OBJECT_MISSING", "RESULT_TREE_GIT_OBJECT_MISSING"] }); assertPass(runLocal(withBindings(repository), [], context, overrides)); } finally { rmSync(repository.root, { recursive: true, force: true }); rmSync(bare, { recursive: true, force: true }); rmSync(context, { recursive: true, force: true }); } });
test("high PASS missing recovery and critical PASS missing rollback fail for the intended rule", () => { const highSol = receipt("sol_acceptance", "ACCEPT"); const high = base({ risk: "high", acceptanceTier: "sol-acceptance", rollback: evidence("PASS"), recovery: evidence("NOT_RUN"), requiredReviewAgents: [{ agent: "terra_reviewer", outcome: "APPROVED" }, { agent: "sol_acceptance", outcome: "ACCEPT" }], reviewReceipts: [receipt(), highSol] }); assertFailure(runLocal(high), "RECOVERY_OR_ROLLBACK_REQUIRED", { exactRules: ["EVIDENCE_INSTANCE_SCHEMA_INVALID", "RECOVERY_OR_ROLLBACK_REQUIRED"] }); const architecture = receipt("sol_architecture_security", "ACCEPT"); const critical = base({ risk: "critical", acceptanceTier: "sol-architecture-security", rollback: evidence("NOT_RUN"), recovery: evidence("PASS"), requiredReviewAgents: [{ agent: "terra_reviewer", outcome: "APPROVED" }, { agent: "terra_security", outcome: "APPROVED" }, { agent: "sol_architecture_security", outcome: "ACCEPT" }], reviewReceipts: [receipt(), receipt("terra_security", "APPROVED"), architecture] }); assertFailure(runLocal(critical), "RECOVERY_OR_ROLLBACK_REQUIRED", { exactRules: ["EVIDENCE_INSTANCE_SCHEMA_INVALID", "RECOVERY_OR_ROLLBACK_REQUIRED"] }); });
test("PASS rollback and recovery reject unexecuted references for high and critical Evidence", () => { const unexecuted = { ...evidence("PASS"), reference: "not-run://fixture" }; for (const risk of ["high", "critical"]) for (const field of ["rollback", "recovery"]) { const solAgent = risk === "high" ? "sol_acceptance" : "sol_architecture_security"; const requiredReviewAgents = [{ agent: "terra_reviewer", outcome: "APPROVED" }, ...(risk === "critical" ? [{ agent: "terra_security", outcome: "APPROVED" }] : []), { agent: solAgent, outcome: "ACCEPT" }]; const reviewReceipts = [receipt(), ...(risk === "critical" ? [receipt("terra_security", "APPROVED")] : []), receipt(solAgent, "ACCEPT")]; const fixture = base({ risk, acceptanceTier: risk === "high" ? "sol-acceptance" : "sol-architecture-security", rollback: evidence("PASS"), recovery: evidence("PASS"), [field]: unexecuted, requiredReviewAgents, reviewReceipts }); assertFailure(runLocal(fixture), "PASS_REFERENCE_NOT_EXECUTED", { exactRules: ["EVIDENCE_INSTANCE_SCHEMA_INVALID", "PASS_REFERENCE_NOT_EXECUTED"] }); } });
test("PASS status rejects unexecuted references on every executed Evidence surface", () => { const unexecuted = "not-run://fixture"; for (const overrides of [{ environments: [{ ...base().environments[0], evidenceRefs: [unexecuted] }] }, { checks: [{ ...base().checks[0], evidenceRef: unexecuted }] }, { negativeScenarios: [{ ...base().negativeScenarios[0], evidenceRef: unexecuted }] }, { ciArtifacts: [{ ...base().ciArtifacts[0], reference: unexecuted }] }, { reviewReceipts: [receipt("terra_reviewer", "APPROVED", { reference: unexecuted })] }]) assertFailure(runLocal(base(overrides)), "PASS_REFERENCE_NOT_EXECUTED", { exactRules: ["EVIDENCE_INSTANCE_SCHEMA_INVALID", "PASS_REFERENCE_NOT_EXECUTED"] }); });
test("[CI] trusted external binding rejects a self-consistent stale manifest", () => { const stale = base({ resultCommit: "d".repeat(40), resultBinding: { kind: "tree", value: "e".repeat(64) }, reviewReceipts: [receipt("terra_reviewer", "APPROVED", { resultCommit: "d".repeat(40), resultTree: "e".repeat(64), reviewedDiffHead: "d".repeat(40) })], ciArtifacts: [{ name: "report.json", reference: ref, binding: { kind: "tree", value: "e".repeat(64) } }] }); const args = ["--expected-source-commit", source, "--expected-result-commit", result, "--expected-result-tree", tree, "--expected-rollback-rehearsal", "not-required", "--expected-recovery-rehearsal", "not-required"]; assertFailure(runCi(stale, args), ["TRUSTED_BINDING_MISMATCH", "TRUSTED_RECEIPT_BINDING_MISMATCH"], { exactRules: ["TRUSTED_BINDING_MISMATCH", "TRUSTED_RECEIPT_BINDING_MISMATCH"] }); });
test("[LOCAL] trusted binding requires a complete source, result, and tree tuple", () => { const partials = [["--expected-source-commit", "d".repeat(40)], ["--expected-result-commit", result], ["--expected-result-tree", tree], ["--expected-source-commit", source, "--expected-result-commit", result], ["--expected-source-commit", source, "--expected-result-tree", tree], ["--expected-result-commit", result, "--expected-result-tree", tree]]; for (const args of partials) assertFailure(runLocal(base(), args), "TRUSTED_BINDING_INCOMPLETE", { exactRules: ["TRUSTED_BINDING_INCOMPLETE"] }); assertPass(runLocal(base(), ["--expected-source-commit", source, "--expected-result-commit", result, "--expected-result-tree", tree])); });
test("[CI] mode requires trusted bindings and both rehearsal expectations", () => { assertFailure(runCi(base(), ["--ci"]), ["TRUSTED_BINDING_REQUIRED", "TRUSTED_REHEARSAL_EXPECTATION_REQUIRED"], { exactRules: ["TRUSTED_BINDING_REQUIRED", "TRUSTED_REHEARSAL_EXPECTATION_REQUIRED"], permitCiFindings: true }); });
test("[CI] mode accepts matching not-required trusted rehearsal expectations", () => { const repository = boundRepository(); try { const args = ["--ci", "--expected-source-commit", repository.sourceCommit, "--expected-result-commit", repository.resultCommit, "--expected-result-tree", repository.resultTree, "--expected-rollback-rehearsal", "not-required", "--expected-recovery-rehearsal", "not-required"]; assertPass(runCi(withBindings(repository), args, repository.root, syntheticCiOverrides(repository.resultCommit))); } finally { rmSync(repository.root, { recursive: true, force: true }); } });
test("[CI] mode rejects missing rehearsal expectations even with trusted Git bindings", () => { const repository = boundRepository(); try { const output = runCi(withBindings(repository), ["--ci", "--expected-source-commit", repository.sourceCommit, "--expected-result-commit", repository.resultCommit, "--expected-result-tree", repository.resultTree], repository.root, syntheticCiOverrides(repository.resultCommit)); assertFailure(output, "TRUSTED_REHEARSAL_EXPECTATION_REQUIRED", { exactRules: ["TRUSTED_REHEARSAL_EXPECTATION_REQUIRED"], permitCiFindings: true }); } finally { rmSync(repository.root, { recursive: true, force: true }); } });
test("[CI] trusted rehearsal inputs reject malformed, mismatched, and required NOT_APPLICABLE declarations", () => { const repository = boundRepository(); try { const bindings = ["--ci", "--expected-source-commit", repository.sourceCommit, "--expected-result-commit", repository.resultCommit, "--expected-result-tree", repository.resultTree]; const ci = syntheticCiOverrides(repository.resultCommit); let output = runCi(withBindings(repository), [...bindings, "--expected-rollback-rehearsal", "maybe", "--expected-recovery-rehearsal", "not-required"], repository.root, ci); assertFailure(output, ["INVALID_TRUSTED_REHEARSAL_EXPECTATION", "TRUSTED_REHEARSAL_EXPECTATION_REQUIRED"], { exactRules: ["INVALID_TRUSTED_REHEARSAL_EXPECTATION", "TRUSTED_REHEARSAL_EXPECTATION_REQUIRED"], permitCiFindings: true }); const mismatch = withBindings(repository, { rollback: evidence("PASS"), recovery: evidence("PASS") }); output = runCi(mismatch, [...bindings, "--expected-rollback-rehearsal", "required", "--expected-recovery-rehearsal", "not-required"], repository.root, ci); assertFailure(output, "TRUSTED_REHEARSAL_EXPECTATION_MISMATCH", { exactRules: ["TRUSTED_REHEARSAL_EXPECTATION_MISMATCH"] }); const sol = receipt("sol_acceptance", "ACCEPT", { sourceCommit: repository.sourceCommit, resultCommit: repository.resultCommit, resultTree: repository.resultTree, reviewedDiffBase: repository.sourceCommit, reviewedDiffHead: repository.resultCommit }); const required = withBindings(repository, { risk: "high", acceptanceTier: "sol-acceptance", rehearsalRequirements: { rollback: true, recovery: false }, rollback: evidence("NOT_APPLICABLE"), recovery: evidence("PASS"), requiredReviewAgents: [{ agent: "terra_reviewer", outcome: "APPROVED" }, { agent: "sol_acceptance", outcome: "ACCEPT" }], reviewReceipts: [withBindings(repository).reviewReceipts[0], sol] }); output = runCi(required, [...bindings, "--expected-rollback-rehearsal", "required", "--expected-recovery-rehearsal", "not-required"], repository.root, ci); assertFailure(output, "NOT_APPLICABLE_REHEARSAL_NOT_PERMITTED", { exactRules: ["EVIDENCE_INSTANCE_SCHEMA_INVALID", "NOT_APPLICABLE_REHEARSAL_NOT_PERMITTED"] }); } finally { rmSync(repository.root, { recursive: true, force: true }); } });
test("legacy one-way rehearsal switches are unsupported", () => { assertFailure(runLocal(base(), ["--rollback-rehearsal-required"]), "EVIDENCE_MANIFEST_CHECK_ERROR", { exactRules: ["EVIDENCE_MANIFEST_CHECK_ERROR"] }); });
test("[CI] trusted binding rejects a missing result commit and a mismatched commit tree", () => { const repository = boundRepository(); try { const missing = "f".repeat(40); const missingBindings = { ...repository, resultCommit: missing }; const rehearsal = ["--expected-rollback-rehearsal", "not-required", "--expected-recovery-rehearsal", "not-required"]; let output = runCi(withBindings(missingBindings), ["--ci", "--expected-source-commit", repository.sourceCommit, "--expected-result-commit", missing, "--expected-result-tree", repository.resultTree, ...rehearsal], repository.root, syntheticCiOverrides(missing)); assertFailure(output, "RESULT_COMMIT_GIT_OBJECT_MISSING", { exactRules: ["RESULT_COMMIT_GIT_OBJECT_MISSING"] }); const wrongTree = { ...repository, resultTree: repository.sourceTree }; output = runCi(withBindings(wrongTree), ["--ci", "--expected-source-commit", repository.sourceCommit, "--expected-result-commit", repository.resultCommit, "--expected-result-tree", repository.sourceTree, ...rehearsal], repository.root, syntheticCiOverrides(repository.resultCommit)); assertFailure(output, "RESULT_COMMIT_TREE_MISMATCH", { exactRules: ["RESULT_COMMIT_TREE_MISMATCH"] }); } finally { rmSync(repository.root, { recursive: true, force: true }); } });
for (const [name, mutate] of [["model", (r) => { delete r.model; }], ["review type", (r) => { delete r.reviewType; }], ["source commit", (r) => { delete r.sourceCommit; }]]) test(`rejects receipt missing ${name}`, () => { const r = receipt(); mutate(r); assertFailure(runLocal(base({ reviewReceipts: [r] })), ["INVALID_REVIEW_RECEIPT_SCHEMA", "MISSING_REQUIRED_REVIEW_RECEIPT"], { exactRules: ["EVIDENCE_INSTANCE_SCHEMA_INVALID", "INVALID_REVIEW_RECEIPT_SCHEMA", "MISSING_REQUIRED_REVIEW_RECEIPT", "PASS_HAS_REQUIRED_EVIDENCE_GAP"] }); });
test("rejects unknown manifest, receipt, and review-type schema values", () => { assertFailure(runLocal(base({ schemaVersion: "hospital-workspace.evidence.v999" })), "UNKNOWN_SCHEMA_VERSION", { exactRules: ["EVIDENCE_INSTANCE_SCHEMA_INVALID", "UNKNOWN_SCHEMA_VERSION"] }); for (const reviewReceipts of [[receipt("terra_reviewer", "APPROVED", { schemaVersion: "hospital-workspace.review-receipt.v999" })], [receipt("terra_reviewer", "APPROVED", { reviewType: "unknown" })]]) assertFailure(runLocal(base({ reviewReceipts })), ["EVIDENCE_INSTANCE_SCHEMA_INVALID", "INVALID_REVIEW_RECEIPT_SCHEMA", "MISSING_REQUIRED_REVIEW_RECEIPT", "PASS_HAS_REQUIRED_EVIDENCE_GAP"], { exactRules: ["EVIDENCE_INSTANCE_SCHEMA_INVALID", "INVALID_REVIEW_RECEIPT_SCHEMA", "MISSING_REQUIRED_REVIEW_RECEIPT", "PASS_HAS_REQUIRED_EVIDENCE_GAP"] }); });
test("rejects missing privacy category", () => { const categories = { ...privacy }; delete categories.phone; assertFailure(runLocal(base({ privacyCategories: categories })), "MISSING_OR_INVALID_PRIVACY_CATEGORY", { exactRules: ["EVIDENCE_INSTANCE_SCHEMA_INVALID", "MISSING_OR_INVALID_PRIVACY_CATEGORY"] }); });
for (const value of [
  [["patient", "name"].join("_"), "synthetic-person"].join("="),
  [["employee", "id"].join("_"), "synthetic-worker"].join("="),
  [["identity", "number"].join("_"), "11010519491231002X"].join("="),
  [["diagnosis"], "synthetic-clinical-text"].join("="),
  [["phone"], "13800138000"].join("="),
  "fixture@example.org",
  [["detailed", "fee"].join("_"), "123.45"].join("="),
  [["cookie"], "abcdefgh"].join("="),
  [["access", "token"].join("_"), "abcdefgh"].join("="),
  [["password"], "abcdefgh"].join("="),
  [["client", "secret"].join("_"), "abcdefgh"].join("="),
  [["private", "key"].join("_"), "abcdefgh"].join("="),
  ["10", "9", "8", "7"].join("."),
  [["clinical", "prompt"].join("_"), "synthetic clinical content"].join("=")
]) test("rejects prohibited privacy content", () => { assertFailure(runLocal(base({ limitations: [value] })), "PROHIBITED_PRIVACY_CONTENT", { exactRules: ["PROHIBITED_PRIVACY_CONTENT"] }); });
for (const [name, value] of [
  ["unkeyed phone", ["Call", "13800138000"].join(" ")],
  ["clinical prompt prose", [["Clinical", "prompt", "content:"].join(" "), "patient-specific details"].join(" ")],
  ["detailed fee prose", [["Detailed", "fee:"].join(" "), "123.45"].join(" ")],
  ["diagnosis clinical prose", [["Diagnosis", "clinical", "text:"].join(" "), "acute condition"].join(" ")],
  ["Bearer JWT-shaped token", [["Bearer"], ["header", "payload", "signature"].join(".")].flat().join(" ")],
  ["Authorization Bearer opaque token", [["Authorization:"], ["opaque", "synthetic", "token"].join("-")].flat().join(" Bearer ")],
  ["Authorization Bearer JWT-shaped token", [["Authorization:"], ["header", "payload", "signature"].join(".")].flat().join(" Bearer ")],
  ["Authorization Basic opaque token", [["Authorization:"], ["opaque", "synthetic", "token"].join("-")].flat().join(" Basic ")],
  ["Authorization Bearer one-character token", [["Authorization:"], "x"].flat().join(" Bearer ")],
  ["Authorization Basic one-character token", [["Authorization:"], "x"].flat().join(" Basic ")],
  ["JWT secret snake", [["jwt", "secret"].join("_"), "abcdefgh"].join("=")],
  ["JWT secret camel", [["jwt", "Secret"].join(""), "abcdefgh"].join("=")],
  ["generic secret", ["secret", "abcdefgh"].join("=")],
  ["credential sentinel still prohibited", ["secret", "example"].join("=")],
  ["unkeyed E.164 phone", ["Call", "+12025550173"].join(" ")],
  ["ULA IPv6", internalIpv6[0]],
  ["link-local IPv6 zone", internalIpv6[1]],
  ["direct patient label", ["Patient", "Alice"].join(": ")],
  ["direct employee label", ["employee", "Alice"].join(" = ")],
  ["direct person label", ["person", "Alice"].join(": ")],
  ["Patient Name label", [["Patient", "Name:"].join(" "), ["Synthetic", "Person"].join(" ")].join(" ")],
  ["Employee Name label", [["Employee", "Name:"].join(" "), ["Synthetic", "Person"].join(" ")].join(" ")],
  ["PGP private-key armor", [["-----BEGIN", "PGP", "PRIVATE", "KEY", "BLOCK-----"].join(" ")].join("")]
]) test(`rejects human-readable prohibited privacy content: ${name}`, () => { assertFailure(runLocal(base({ limitations: [value] })), "PROHIBITED_PRIVACY_CONTENT", { exactRules: ["PROHIBITED_PRIVACY_CONTENT"] }); });
test("does not expose labeled authorization or E.164 values in manifest output", () => { for (const value of [[["Authorization:"], "x"].flat().join(" Bearer "), ["Call", "+12025550173"].join(" ")]) { const output = runLocal(base({ limitations: [value] })); assertFailure(output, "PROHIBITED_PRIVACY_CONTENT", { exactRules: ["PROHIBITED_PRIVACY_CONTENT"] }); assert.doesNotMatch(output.stdout, /Authorization|Bearer|12025550173/); } });
test("does not expose JWT or generic secret assignment values in manifest output", () => { const jwt = ["jwt", "secret"].join("_"); const generic = ["secret", "="].join(""); const redacted = new RegExp(["abcdefgh", jwt, generic].join("|"), "i"); for (const value of [[jwt, "abcdefgh"].join("="), ["secret", "abcdefgh"].join("=")]) { const output = runLocal(base({ limitations: [value] })); assertFailure(output, "PROHIBITED_PRIVACY_CONTENT", { exactRules: ["PROHIBITED_PRIVACY_CONTENT"] }); assert.doesNotMatch(output.stdout, redacted); } });
test("does not expose direct patient, employee, or person labels in manifest output", () => { for (const value of [["Patient", "Alice"].join(": "), ["employee", "Alice"].join(" = "), ["person", "Alice"].join(": ")]) { const output = runLocal(base({ limitations: [value] })); assertFailure(output, "PROHIBITED_PRIVACY_CONTENT", { exactRules: ["PROHIBITED_PRIVACY_CONTENT"] }); assert.doesNotMatch(output.stdout, /Alice|Patient|employee|person/i); } });
test("[LOCAL] permits ordinary prose that mentions Authorization Bearer without a credential value", () => { assertPass(runLocal(base({ limitations: [["Authorization", "Bearer", "tokens", "require", "redaction."].join(" ")] }))); });
test("[LOCAL] permits ordinary policy prose that mentions patient, employee, and person without an assignment", () => { assertPass(runLocal(base({ limitations: [["Patient", "employee", "and", "person", "data", "remain", "prohibited."].join(" ")] }))); });
test("[LOCAL] permits public and documentation IPv6 addresses", () => { for (const value of ["2001:db8::1", "2001:4860:4860::8888"]) assertPass(runLocal(base({ limitations: [value] }))); });
test("rejects compressed, full, bracketed, zoned, and CIDR ULA or link-local IPv6", () => { for (const value of internalIpv6) assertFailure(runLocal(base({ limitations: [value] })), "PROHIBITED_PRIVACY_CONTENT", { exactRules: ["PROHIBITED_PRIVACY_CONTENT"] }); });
test("[LOCAL] permits IPv6 values immediately outside ULA and link-local ranges", () => { for (const value of [ipv6("FBFF", "", "1"), ipv6("FEC0", "", "1"), "2001:db8::1", "2001:4860:4860::8888"]) assertPass(runLocal(base({ limitations: [value] }))); });
const ipv4 = (...octets) => octets.join("."); const cidr = (address, prefix) => `${address}/${prefix}`;
for (const value of [ipv4("10", "0", "0", "8"), cidr(ipv4("10", "0", "0", "0"), "24"), `${ipv4("10", "0", "0", "8")}.`, `${cidr(ipv4("10", "0", "0", "0"), "24")}.`, `tag-${ipv4("10", "0", "0", "8")}`]) test(`[LOCAL] permits canonical synthetic IPv4 value ${value}`, () => { assertPass(runLocal(base({ limitations: [value] }))); });
for (const value of [cidr(ipv4("10", "0", "0", "8"), "8"), cidr(ipv4("10", "0", "0", "8"), "24"), cidr(ipv4("10", "0", "0", "0"), "8"), cidr(cidr(ipv4("10", "0", "0", "0"), "24"), "extra"), cidr(cidr(ipv4("10", "0", "0", "0"), "24"), ""), ipv4("10", "0", "1", "8"), `${ipv4("10", "0", "1", "8")}.`, `tag-${ipv4("10", "0", "1", "8")}`, `tag_${ipv4("10", "0", "1", "8")}`, `.${ipv4("10", "0", "1", "8")}`, cidr(ipv4("10", "0", "0", "1"), "16"), ipv4("192", "168", "1", "1"), `${ipv4("192", "168", "1", "1")}.`, ipv4("172", "16", "0", "1"), ipv4("10", "0", "0", "256"), `${ipv4("1", "2", "3", "4")}.5`, cidr(ipv4("10", "0", "0", "1"), "33"), cidr(ipv4("10", "0", "0", "1"), "-1"), cidr(ipv4("10", "0", "0", "1"), "024"), cidr(ipv4("203", "0", "113", "1"), "24")]) test(`[LOCAL] rejects noncanonical or private IPv4 value ${value}`, () => { assertFailure(runLocal(base({ limitations: [value] })), "PROHIBITED_PRIVACY_CONTENT", { exactRules: ["PROHIBITED_PRIVACY_CONTENT"] }); });
test("rejects invalid Linux, WSL, and mock environment claims for the intended overclaim rule", () => { const related = ["INVALID_CHECK", "INVALID_ENVIRONMENT", "MISSING_REQUIRED_CHECK", "PASS_HAS_REQUIRED_EVIDENCE_GAP"]; for (const [env, rule] of [[{ id: "ubuntu-ci", required: true, status: "PASS", claims: ["ubuntu-ci", "windows-tauri-webview2-msi"], evidenceRefs: [ref] }, "UBUNTU_PLATFORM_OVERCLAIM"], [{ id: "wsl2", required: false, status: "PASS", claims: ["physical-anolis"], evidenceRefs: [ref] }, "WSL_ANOLIS_OVERCLAIM"], [{ id: "mock-integration", required: false, status: "PASS", claims: ["mock-integration", "real-upstream-his"], evidenceRefs: [ref] }, "MOCK_UPSTREAM_OVERCLAIM"]]) assertFailure(runLocal(base({ environments: [env] })), rule, { exactRules: [rule, ...related] }); });
test("[ISOLATION] host CI=true does not change a LOCAL positive fixture", () => { assertPass(runLocal(base(), [], null, {}, { ...process.env, CI: "true" })); });
test("[ISOLATION] host GITHUB_ACTIONS=true does not change LOCAL mode", () => { assertPass(runLocal(base(), [], null, {}, { ...process.env, GITHUB_ACTIONS: "true" })); });
test("[ISOLATION] host HW_CI variables do not change LOCAL mode", () => { const host = { ...process.env, HW_CI_COMMIT_SHA: source, HW_CI_RUN_ID: "9002", HW_CI_RUN_ATTEMPT: "2", HW_CI_BASE_SHA: source, HW_CI_HEAD_SHA: result, HW_CI_EVENT_NAME: "pull_request", HW_CI_REHEARSAL_EXPECTED: "required", HW_CI_RECOVERY_EXPECTED: "required" }; assertPass(runLocal(base(), [], null, {}, host)); });
test("[ISOLATION] a fully polluted CI GitHub and HW_CI host still yields a clean LOCAL mode", () => { const host = { ...process.env, ...Object.fromEntries(EVIDENCE_CHECKER_HOST_CONTROL_KEYS.map((key) => [key, "synthetic-host-value"])), CI: "true", GITHUB_ACTIONS: "true" }; assertPass(runLocal(base(), [], null, {}, host)); });
test("[CI] explicit mode without trusted manifest bindings fails closed", () => { assertFailure(runCi(base()), ["TRUSTED_BINDING_REQUIRED", "TRUSTED_REHEARSAL_EXPECTATION_REQUIRED"], { exactRules: ["TRUSTED_BINDING_REQUIRED", "TRUSTED_REHEARSAL_EXPECTATION_REQUIRED"], permitCiFindings: true }); });
test("[CI] explicit mode with complete trusted bindings passes", () => { const repository = boundRepository(); try { const args = ["--expected-source-commit", repository.sourceCommit, "--expected-result-commit", repository.resultCommit, "--expected-result-tree", repository.resultTree, "--expected-rollback-rehearsal", "not-required", "--expected-recovery-rehearsal", "not-required"]; assertPass(runCi(withBindings(repository), args, repository.root, syntheticCiOverrides(repository.resultCommit))); } finally { rmSync(repository.root, { recursive: true, force: true }); } });
test("[ISOLATION] LOCAL mode does not inherit GIT_DIR", () => { const host = { ...process.env, GIT_DIR: join(tmpdir(), "missing-host-git-dir") }; const environment = buildEvidenceCheckerTestEnvironment({ mode: "LOCAL", hostEnvironment: host }); assert.equal(Object.hasOwn(environment, "GIT_DIR"), false); assertPass(runLocal(base(), [], null, {}, host)); });
test("[ISOLATION] LOCAL mode does not inherit GIT_WORK_TREE", () => { const host = { ...process.env, GIT_WORK_TREE: join(tmpdir(), "missing-host-work-tree") }; const environment = buildEvidenceCheckerTestEnvironment({ mode: "LOCAL", hostEnvironment: host }); assert.equal(Object.hasOwn(environment, "GIT_WORK_TREE"), false); assertPass(runLocal(base(), [], null, {}, host)); });
test("[ISOLATION] concurrent LOCAL and CI checker subprocesses do not pollute one another", async () => { const host = { ...process.env, CI: "true", GITHUB_ACTIONS: "true", HW_CI_COMMIT_SHA: result, HW_CI_RUN_ID: "9003", HW_CI_RUN_ATTEMPT: "3" }; const [local, ci] = await Promise.all([runAsync(base(), [], null, { mode: "LOCAL", hostEnvironment: host }), runAsync(base(), [], null, { mode: "CI", overrides: syntheticCiOverrides(), hostEnvironment: host })]); assertPass(local); assertFailure(ci, ["TRUSTED_BINDING_REQUIRED", "TRUSTED_REHEARSAL_EXPECTATION_REQUIRED"], { exactRules: ["TRUSTED_BINDING_REQUIRED", "TRUSTED_REHEARSAL_EXPECTATION_REQUIRED"], permitCiFindings: true }); });
test("[ISOLATION] checker subprocess environment excludes an unauthorized secret", () => { const secretKey = ["HW_TEST_UNAUTHORIZED", "SECRET"].join("_"); const hostEnvironment = { ...process.env, [secretKey]: "do-not-propagate" }; const environment = buildEvidenceCheckerTestEnvironment({ mode: "LOCAL", hostEnvironment }); assert.equal(Object.hasOwn(environment, secretKey), false); const probe = spawnSync(process.execPath, ["-e", "process.stdout.write(String(Object.hasOwn(process.env, process.argv[1])))", secretKey], { encoding: "utf8", env: environment }); assert.equal(probe.status, 0, probe.stderr); assert.equal(probe.stdout, "false"); });
test("[LOCAL] positive checker output contains no findings", () => { assertPass(runLocal(base())); });
test("[LOCAL] negative checker output contains only the expected privacy finding", () => { assertFailure(runLocal(base({ limitations: ["phone: 202-555-0173"] })), "PROHIBITED_PRIVACY_CONTENT", { exactRules: ["PROHIBITED_PRIVACY_CONTENT"] }); });

// HW00-06R-02 decision/review contract fixtures. These exercise the checker CLI seam.
function assertRejected(output) { assert.notEqual(output.status, 0, output.stdout); const parsed = report(output); assert.equal(parsed.status, "FAIL", output.stdout); assert.ok(parsed.findings.length > 0, output.stdout); assert.ok(parsed.findings.every((finding) => ["path,rule", "instancePath,keyword,rule,schemaPath"].includes(Object.keys(finding).sort().join(","))), output.stdout); return parsed; }
function requiredEvidenceFixture(status, overrides = {}) { return base({ environments: [{ ...base().environments[0], status }], checks: [{ ...base().checks[0], status }], negativeScenarios: [{ ...base().negativeScenarios[0], status }], decision: "CONDITIONAL", ...overrides }); }
for (const status of ["FAIL", "BLOCKED", "NOT_RUN"]) test(`CONDITIONAL rejects required evidence status ${status}`, () => { assertRejected(runLocal(requiredEvidenceFixture(status))); });
test("CONDITIONAL rejects a missing required check", () => { assertRejected(runLocal(base({ decision: "CONDITIONAL", checks: [] }))); });
test("CONDITIONAL rejects a Terra CHANGES_REQUESTED receipt", () => { assertRejected(runLocal(base({ decision: "CONDITIONAL", reviewReceipts: [receipt("terra_reviewer", "CHANGES_REQUESTED")] }))); });
test("CONDITIONAL accepts a phase gate CONDITIONAL_RECOMMENDED result when required evidence is valid", () => { const phase = base({ scope: { kind: "phase", phaseId: "HW-00", taskId: null }, acceptanceTier: "sol-phase-gate", decision: "CONDITIONAL", requiredReviewAgents: [{ agent: "terra_reviewer", outcome: "APPROVED" }, { agent: "terra_security", outcome: "APPROVED" }, { agent: "sol_phase_gate", outcome: "PASS_RECOMMENDED" }], reviewReceipts: [receipt("terra_reviewer", "APPROVED"), receipt("terra_security", "APPROVED", { reviewType: "security" }), receipt("sol_phase_gate", "CONDITIONAL_RECOMMENDED", { reviewType: "phase-gate" })] }); assertPass(runLocal(phase)); });
test("BLOCKED accepts a failed required check as a genuine blocker", () => { assertPass(runLocal(base({ decision: "BLOCKED", checks: [{ ...base().checks[0], status: "FAIL" }] }))); });
test("BLOCKED rejects a record with no genuine blocker", () => { assertRejected(runLocal(base({ decision: "BLOCKED" }))); });
test("PASS rejects every non-PASS required environment, check, and negative scenario", () => { for (const field of ["environments", "checks", "negativeScenarios"]) { const current = base()[field][0]; assertRejected(runLocal(base({ [field]: [{ ...current, status: "FAIL" }] }))); } });
for (const [agent, outcome, reviewType] of [["terra_reviewer", "CHANGES_REQUESTED", "implementation"], ["sol_acceptance", "REJECT", "acceptance"], ["sol_acceptance", "BLOCKED", "acceptance"]]) test(`BLOCKED preserves negative ${agent} ${outcome} receipt`, () => { const isSol = agent === "sol_acceptance"; const manifest = base({ decision: "BLOCKED", ...(isSol ? { risk: "high", acceptanceTier: "sol-acceptance", requiredReviewAgents: [{ agent: "terra_reviewer", outcome: "APPROVED" }, { agent, outcome: "ACCEPT" }], reviewReceipts: [receipt("terra_reviewer", "APPROVED"), receipt(agent, outcome, { reviewType })] } : { reviewReceipts: [receipt(agent, outcome, { reviewType })] }) }); assertPass(runLocal(manifest)); });
test("BLOCKED preserves a phase-gate BLOCKED receipt", () => { const phase = base({ scope: { kind: "phase", phaseId: "HW-00", taskId: null }, acceptanceTier: "sol-phase-gate", decision: "BLOCKED", requiredReviewAgents: [{ agent: "terra_reviewer", outcome: "APPROVED" }, { agent: "terra_security", outcome: "APPROVED" }, { agent: "sol_phase_gate", outcome: "PASS_RECOMMENDED" }], reviewReceipts: [receipt("terra_reviewer", "APPROVED"), receipt("terra_security", "APPROVED", { reviewType: "security" }), receipt("sol_phase_gate", "BLOCKED", { reviewType: "phase-gate" })] }); assertPass(runLocal(phase)); });
test("PASS rejects negative review outcomes", () => { for (const [agent, outcome, reviewType] of [["terra_reviewer", "CHANGES_REQUESTED", "implementation"], ["sol_acceptance", "REJECT", "acceptance"], ["sol_phase_gate", "CONDITIONAL_RECOMMENDED", "phase-gate"]]) { const isPhase = agent === "sol_phase_gate"; const manifest = base({ ...(isPhase ? { scope: { kind: "phase", phaseId: "HW-00", taskId: null }, acceptanceTier: "sol-phase-gate", requiredReviewAgents: [{ agent: "terra_reviewer", outcome: "APPROVED" }, { agent: "terra_security", outcome: "APPROVED" }, { agent, outcome: "PASS_RECOMMENDED" }], reviewReceipts: [receipt("terra_reviewer", "APPROVED"), receipt("terra_security", "APPROVED", { reviewType: "security" }), receipt(agent, outcome, { reviewType })] } : { reviewReceipts: [receipt(agent, outcome, { reviewType })] }) }); assertRejected(runLocal(manifest)); } });
test("PASS and CONDITIONAL reject additional negative review receipts", () => { const additionalReject = receipt("sol_acceptance", "REJECT", { reviewType: "acceptance" }); assertFailure(runLocal(base({ reviewReceipts: [receipt(), additionalReject] })), "PASS_HAS_NEGATIVE_REVIEW_OUTCOME", { exactRules: ["PASS_HAS_NEGATIVE_REVIEW_OUTCOME"] }); const additionalSecurityRejection = receipt("terra_security", "CHANGES_REQUESTED", { reviewType: "security" }); assertFailure(runLocal(base({ decision: "CONDITIONAL", reviewReceipts: [receipt(), additionalSecurityRejection] })), "CONDITIONAL_HAS_NEGATIVE_REVIEW_OUTCOME", { exactRules: ["CONDITIONAL_HAS_NEGATIVE_REVIEW_OUTCOME"] }); });
test("PASS and task CONDITIONAL reject undeclared phase-gate conditional recommendations", () => { const optionalPhaseRecommendation = receipt("sol_phase_gate", "CONDITIONAL_RECOMMENDED", { reviewType: "phase-gate" }); assertFailure(runLocal(base({ reviewReceipts: [receipt(), optionalPhaseRecommendation] })), "PASS_HAS_NEGATIVE_REVIEW_OUTCOME", { exactRules: ["PASS_HAS_NEGATIVE_REVIEW_OUTCOME"] }); assertFailure(runLocal(base({ decision: "CONDITIONAL", reviewReceipts: [receipt(), optionalPhaseRecommendation] })), "CONDITIONAL_HAS_NEGATIVE_REVIEW_OUTCOME", { exactRules: ["CONDITIONAL_HAS_NEGATIVE_REVIEW_OUTCOME"] }); });
test("rejects wrong agent/outcome combinations and missing required receipts", () => { assertRejected(runLocal(base({ reviewReceipts: [receipt("terra_reviewer", "ACCEPT")] }))); assertRejected(runLocal(base({ reviewReceipts: [] }))); });
function assertSchemaFinding(output, rule) { const parsed = assertRejected(output); const schemaFindings = parsed.findings.filter((finding) => finding.rule === rule); assert.ok(schemaFindings.length > 0, output.stdout); for (const finding of schemaFindings) { assert.deepEqual(Object.keys(finding).sort(), ["instancePath", "keyword", "rule", "schemaPath"]); assert.doesNotMatch(JSON.stringify(finding), /Synthetic fixture|abcdefgh|hospital-workspace\.evidence\.v3/i); } return parsed; }
test("standards-compliant validator accepts the complete Draft 2020-12 schema and example", () => { assertPass(runSchemaVariant(base(), () => {})); });
for (const [name, mutate, rule] of [["missing reviewReceipt definition", (candidate) => { delete candidate.$defs.reviewReceipt; }, "JSON_SCHEMA_COMPILE_ERROR"], ["unresolved reference", (candidate) => { candidate.properties.reviewReceipts.items.$ref = "#/$defs/missingReviewReceipt"; }, "JSON_SCHEMA_COMPILE_ERROR"], ["invalid keyword type", (candidate) => { candidate.properties.branch.type = { invalid: true }; }, "JSON_SCHEMA_META_INVALID"], ["invalid root required definition", (candidate) => { candidate.required = "schemaVersion"; }, "JSON_SCHEMA_META_INVALID"]]) test(`schema ${name} fails closed`, () => { assertSchemaFinding(runSchemaVariant(base(), mutate), rule); });
test("schema example missing required field fails instance validation", () => { const candidate = base(); delete candidate.program; assertSchemaFinding(runSchemaVariant(candidate, () => {}), "EVIDENCE_INSTANCE_SCHEMA_INVALID"); });
test("schema example invalid enum fails instance validation", () => { assertSchemaFinding(runSchemaVariant(base({ risk: "unsupported" }), () => {}), "EVIDENCE_INSTANCE_SCHEMA_INVALID"); });
test("schema example wrong agent/outcome pair fails instance validation", () => { assertSchemaFinding(runSchemaVariant(base({ reviewReceipts: [receipt("terra_reviewer", "ACCEPT")] }), () => {}), "EVIDENCE_INSTANCE_SCHEMA_INVALID"); });
test("schema example malformed date-time fails instance validation", () => { assertSchemaFinding(runSchemaVariant(base({ decidedAt: "2026-08-31" }), () => {}), "EVIDENCE_INSTANCE_SCHEMA_INVALID"); });
test("schema compile exception fails closed with sanitized schema findings", () => { assertSchemaFinding(runSchemaVariant(base(), (candidate) => { candidate.$defs.reviewReceipt = { type: "string", allOf: [{ $ref: "#/$defs/does-not-exist" }] }; }), "JSON_SCHEMA_COMPILE_ERROR"); });

test("PASS accepts the required Terra reviewer with its configured model", () => { assertPass(runLocal(base({ reviewReceipts: [receipt("terra_reviewer", "APPROVED", { model: "gpt-5.6-terra" })] }))); });
test("critical PASS accepts Terra security and Sol architecture-security with configured models", () => { const manifest = base({ risk: "critical", acceptanceTier: "sol-architecture-security", rollback: evidence("PASS"), recovery: evidence("PASS"), requiredReviewAgents: [{ agent: "terra_reviewer", outcome: "APPROVED" }, { agent: "terra_security", outcome: "APPROVED" }, { agent: "sol_architecture_security", outcome: "ACCEPT" }], reviewReceipts: [receipt("terra_reviewer"), receipt("terra_security", "APPROVED", { reviewType: "security" }), receipt("sol_architecture_security", "ACCEPT", { reviewType: "architecture-security" })] }); assertPass(runLocal(manifest)); });
test("phase PASS accepts Sol phase-gate PASS_RECOMMENDED with its configured model", () => { const manifest = base({ scope: { kind: "phase", phaseId: "HW-00", taskId: null }, acceptanceTier: "sol-phase-gate", requiredReviewAgents: [{ agent: "terra_reviewer", outcome: "APPROVED" }, { agent: "terra_security", outcome: "APPROVED" }, { agent: "sol_phase_gate", outcome: "PASS_RECOMMENDED" }], reviewReceipts: [receipt("terra_reviewer"), receipt("terra_security", "APPROVED", { reviewType: "security" }), receipt("sol_phase_gate", "PASS_RECOMMENDED", { reviewType: "phase-gate" })] }); assertPass(runLocal(manifest)); });
test("BLOCKED accepts empty reviewReceipts when a declared required review is absent", () => { const manifest = base({ decision: "BLOCKED", requiredReviewAgents: [{ agent: "terra_reviewer", outcome: "APPROVED" }, { agent: "terra_security", outcome: "APPROVED" }], reviewReceipts: [] }); assertPass(runLocal(manifest)); });
test("BLOCKED preserves valid negative Terra and Sol receipts", () => { const terra = base({ decision: "BLOCKED", reviewReceipts: [receipt("terra_reviewer", "CHANGES_REQUESTED")] }); assertPass(runLocal(terra)); const sol = base({ decision: "BLOCKED", risk: "high", acceptanceTier: "sol-acceptance", requiredReviewAgents: [{ agent: "terra_reviewer", outcome: "APPROVED" }, { agent: "sol_acceptance", outcome: "ACCEPT" }], reviewReceipts: [receipt("terra_reviewer"), receipt("sol_acceptance", "BLOCKED", { reviewType: "acceptance" })] }); assertPass(runLocal(sol)); });
test("wrong reviewer models fail closed and do not satisfy PASS or CONDITIONAL", () => { const cases = [["sol_acceptance", "gpt-5.6-terra", "ACCEPT"], ["sol_architecture_security", "gpt-5.6-terra", "ACCEPT"], ["sol_phase_gate", "gpt-5.6-terra", "PASS_RECOMMENDED"], ["terra_reviewer", "gpt-5.6-sol", "APPROVED"], ["terra_security", "gpt-5.6-sol", "APPROVED"], ["terra_reviewer", "gpt-5.6-terra-alias", "APPROVED"], ["terra_reviewer", "GPT-5.6-TERRA", "APPROVED"], ["terra_reviewer", " gpt-5.6-terra", "APPROVED"], ["terra_reviewer", "gpt-5.6-terra ", "APPROVED"], ["terra_reviewer", "", "APPROVED"]]; const withoutSchemaModelConstraints = (candidate) => { for (const clause of candidate.$defs.reviewReceipt.allOf) delete clause.then.properties.model; }; for (const [agent, model, outcome] of cases) { const reviewType = agent.startsWith("sol_") ? (agent === "sol_phase_gate" ? "phase-gate" : "acceptance") : "implementation"; const requiredOutcome = agent === "sol_phase_gate" ? "PASS_RECOMMENDED" : agent.startsWith("sol_") ? "ACCEPT" : "APPROVED"; const receiptValue = receipt(agent, outcome, { model, reviewType }); const manifest = base({ requiredReviewAgents: [{ agent, outcome: requiredOutcome }], reviewReceipts: [receiptValue] }); const parsed = assertRejected(runLocal(manifest)); assert.ok(parsed.findings.some((finding) => finding.rule === "EVIDENCE_INSTANCE_SCHEMA_INVALID" || finding.rule === "INVALID_REVIEW_RECEIPT_SCHEMA"), `${agent}/${model}: ${JSON.stringify(parsed)}`); if (model) { const semantic = assertRejected(runSchemaVariant(manifest, withoutSchemaModelConstraints)); assert.ok(semantic.findings.some((finding) => finding.rule === "REVIEW_MODEL_MISMATCH"), `${agent}/${model}: ${JSON.stringify(semantic)}`); assert.ok(semantic.findings.some((finding) => finding.rule === "MISSING_REQUIRED_REVIEW_RECEIPT"), `${agent}/${model}: ${JSON.stringify(semantic)}`); const conditional = base({ decision: "CONDITIONAL", requiredReviewAgents: [{ agent, outcome: requiredOutcome }], reviewReceipts: [receiptValue] }); const conditionalParsed = assertRejected(runSchemaVariant(conditional, withoutSchemaModelConstraints)); assert.ok(conditionalParsed.findings.some((finding) => finding.rule === "REVIEW_MODEL_MISMATCH"), `${agent}/${model}: ${JSON.stringify(conditionalParsed)}`); } } });
test("wrong-model positive receipt remains a genuine blocker without being counted", () => { const manifest = base({ decision: "BLOCKED", reviewReceipts: [receipt("terra_reviewer", "APPROVED", { model: "gpt-5.6-sol" })] }); const parsed = assertRejected(runLocal(manifest)); assert.ok(parsed.findings.some((finding) => finding.rule === "REVIEW_MODEL_MISMATCH"), JSON.stringify(parsed)); });
test("Schema and semantic validation both reject a wrong model", () => { const manifest = base({ reviewReceipts: [receipt("terra_reviewer", "APPROVED", { model: "gpt-5.6-sol" })] }); const direct = assertRejected(runLocal(manifest)); assert.ok(direct.findings.some((finding) => finding.rule === "REVIEW_MODEL_MISMATCH"), JSON.stringify(direct)); const schemaOnly = assertSchemaFinding(runSchemaVariant(manifest, () => {}), "EVIDENCE_INSTANCE_SCHEMA_INVALID"); assert.ok(schemaOnly.findings.some((finding) => finding.rule === "EVIDENCE_INSTANCE_SCHEMA_INVALID"), JSON.stringify(schemaOnly)); });
test("PASS and CONDITIONAL reject empty reviewReceipts", () => { for (const decision of ["PASS", "CONDITIONAL"]) assertRejected(runLocal(base({ decision, reviewReceipts: [] }))); });
test("PASS and CONDITIONAL reject one missing declared required review", () => { const requiredReviewAgents = [{ agent: "terra_reviewer", outcome: "APPROVED" }, { agent: "terra_security", outcome: "APPROVED" }]; const receipts = [receipt("terra_reviewer")]; for (const decision of ["PASS", "CONDITIONAL"]) { const parsed = assertRejected(runLocal(base({ decision, requiredReviewAgents, reviewReceipts: receipts }))); assert.ok(parsed.findings.some((finding) => finding.rule === "MISSING_REQUIRED_REVIEW_RECEIPT"), JSON.stringify(parsed)); } });
test("unknown model and explicit model alias are rejected as distinct fixtures", () => { for (const model of ["model.unknown.synthetic", "gpt-5.6-terra-alias"]) { const parsed = assertRejected(runLocal(base({ reviewReceipts: [receipt("terra_reviewer", "APPROVED", { model })] }))); assert.ok(parsed.findings.some((finding) => finding.rule === "EVIDENCE_INSTANCE_SCHEMA_INVALID" || finding.rule === "INVALID_REVIEW_RECEIPT_SCHEMA"), JSON.stringify(parsed)); } });
