import assert from "node:assert/strict";
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import test from "node:test";
import { verifyEventDiff } from "./run-foundation-checks.mjs";

const here = dirname(fileURLToPath(import.meta.url)); const runner = resolve(here, "run-foundation-checks.mjs"); const workflow = resolve(here, "../../.github/workflows/checks.yml");
const OFFICIAL_ACTIONS = new Map([
  ["actions/checkout", ["11d5960a326750d5838078e36cf38b85af677262", "v4.4.0"]],
  ["actions/setup-node", ["49933ea5288caeca8642d1e84afbd3f7d6820020", "v4.4.0"]],
  ["pnpm/action-setup", ["fc06bc1257f339d1d5d8b3a19a8cae5388b55320", "v4.4.0"]],
  ["actions/setup-python", ["a26af69be951a213d495a4c3e4e4022e16d87065", "v5.6.0"]],
  ["actions/upload-artifact", ["ea165f8d65b6e75b540449e92b4886f43607fa02", "v4.6.2"]]
]);
function structuredUses(text) { const program = "import sys,json,yaml\ndef walk(value):\n if isinstance(value,dict):\n  for key,item in value.items():\n   if key == 'uses' and isinstance(item,str): yield item\n   yield from walk(item)\n elif isinstance(value,list):\n  for item in value: yield from walk(item)\nprint(json.dumps(list(walk(yaml.safe_load(sys.stdin.read())))))"; const parsed = spawnSync("python", ["-c", program], { input: text, encoding: "utf8" }); assert.equal(parsed.status, 0, parsed.stderr); return JSON.parse(parsed.stdout); }
function sourceUses(text) { return [...text.matchAll(/^\s*(?:"uses"|'uses'|uses)\s*:\s*(?:"([^"]+)"|'([^']+)'|([^\s#][^#]*?))\s*(?:#\s*(v\d+\.\d+\.\d+)(?:\s+#.*)?)?\s*$/gm)].map((match) => ({ reference: (match[1] ?? match[2] ?? match[3]).trim(), version: match[4] ?? null })); }
function validateUses(text) { const structured = structuredUses(text); const annotated = sourceUses(text); const pending = structured.filter((reference) => !reference.startsWith("./")); let remoteCount = 0; for (const reference of pending) { const separator = reference.lastIndexOf("@"); assert.notEqual(separator, -1, reference); const repository = reference.slice(0, separator); const revision = reference.slice(separator + 1); const expected = OFFICIAL_ACTIONS.get(repository); assert.ok(expected, `unapproved Action repository: ${repository}`); assert.equal(revision, expected[0], `unpinned Action: ${reference}`); const index = annotated.findIndex((entry) => entry.reference === reference); assert.notEqual(index, -1, `remote Action omitted from source annotation validation: ${reference}`); assert.equal(annotated[index].version, expected[1], `missing or stale version comment: ${reference}`); annotated.splice(index, 1); remoteCount += 1; } assert.equal(annotated.filter((entry) => !entry.reference.startsWith("./")).length, 0, "unparsed remote uses source entry"); return remoteCount; }
function git(root, args) { const result = spawnSync("git", args, { cwd: root, encoding: "utf8" }); assert.equal(result.status, 0, result.stderr); return result.stdout.trim(); }
function repo({ whitespace = false } = {}) { const root = mkdtempSync(join(tmpdir(), "hospital-workspace-diff-")); git(root, ["init", "--quiet"]); git(root, ["config", "user.email", "fixture@example.invalid"]); git(root, ["config", "user.name", "Fixture"]); writeFileSync(join(root, "file.txt"), "base\n"); git(root, ["add", "file.txt"]); git(root, ["commit", "--quiet", "-m", "base"]); const base = git(root, ["rev-parse", "HEAD"]); writeFileSync(join(root, "file.txt"), whitespace ? "base\ntrailing \n" : "base\nhead\n"); git(root, ["add", "file.txt"]); git(root, ["commit", "--quiet", "-m", "head"]); return { root, base, head: git(root, ["rev-parse", "HEAD"]) }; }
function event(root, payload) { const path = join(root, "event.json"); writeFileSync(path, JSON.stringify(payload)); return path; }
test("workflow pins only official Actions, disables checkout credentials, and retains gate shape", () => { const yaml = spawnSync("python", ["-c", "import sys, yaml; yaml.safe_load(open(sys.argv[1], encoding='utf-8'))", workflow], { encoding: "utf8" }); assert.equal(yaml.status, 0, yaml.stderr); const text = read(workflow); assert.equal(validateUses(text), 5); assert.match(text, /^name: checks$/m); assert.match(text, /^jobs:\s*\n  checks:\s*\n    name: checks$/m); assert.match(text, /^permissions:\s*\n  contents: read$/m); assert.match(text, /^  pull_request:$/m); assert.match(text, /^  push:\s*\n    branches:\s*\n      - main$/m); assert.match(text, /persist-credentials: false/); assert.match(text, /fetch-depth: 0/); assert.match(text, /path: \$\{\{ runner\.temp \}\}\/hospital-workspace-checks/); assert.match(text, /if-no-files-found: error/); assert.doesNotMatch(text, /pull_request_target|secrets\.|continue-on-error|credential\.helper|git push|git fetch https/i); });
test("remote Action validator rejects floating, abbreviated, substituted, quoted, trailing-comment, and inline references", () => { const checkout = OFFICIAL_ACTIONS.get("actions/checkout"); for (const workflowText of ["uses: actions/checkout@v1 # v1.0.0\n", "uses: actions/checkout@v4 # v4.4.0\n", "uses: actions/checkout@main # v4.4.0\n", "uses: actions/checkout@master # v4.4.0\n", `uses: actions/checkout@${checkout[0].slice(0, 12)} # v4.4.0\n`, `uses: ${["example", "checkout"].join("/")}@${checkout[0]} # v4.4.0\n`, `uses: evil/example@0123456789012345678901234567890123456789 # v0.0.0 # trailing\n`, `\"uses\": \"evil/example@0123456789012345678901234567890123456789\" # v0.0.0 # trailing\n`, "- { uses: \"evil/example@0123456789012345678901234567890123456789\" } # v0.0.0\n"]) assert.throws(() => validateUses(workflowText)); assert.equal(validateUses("uses: ./local-action\n"), 0); });
function read(path) { return (awaitRead(path)); } function awaitRead(path) { return spawnSync("node", ["-e", "process.stdout.write(require('fs').readFileSync(process.argv[1],'utf8'))", path], { encoding: "utf8" }).stdout; }
test("real PR and push diffs record trusted metadata", () => { const f = repo(); try { const pr = verifyEventDiff(f.root, { GITHUB_EVENT_NAME: "pull_request", GITHUB_EVENT_PATH: event(f.root, { pull_request: { base: { sha: f.base }, head: { sha: f.head } } }) }); assert.deepEqual({ eventType: pr.eventType, base: pr.base, head: pr.head, diffMode: pr.diffMode, exitCode: pr.exitCode }, { eventType: "pull_request", base: f.base, head: f.head, diffMode: "three-dot", exitCode: 0 }); const push = verifyEventDiff(f.root, { GITHUB_EVENT_NAME: "push", GITHUB_EVENT_PATH: event(f.root, { before: f.base, after: f.head }) }); assert.equal(push.diffMode, "two-dot"); assert.equal(push.changedFileCount, 1); } finally { rmSync(f.root, { recursive: true, force: true }); } });
test("initial push compares the complete head tree to an empty tree", () => { const f = repo(); try { const output = verifyEventDiff(f.root, { GITHUB_EVENT_NAME: "push", GITHUB_EVENT_PATH: event(f.root, { before: "0".repeat(40), after: f.head }) }); assert.equal(output.diffMode, "empty-tree"); assert.equal(output.changedFileCount, 1); assert.equal(output.exitCode, 0); } finally { rmSync(f.root, { recursive: true, force: true }); } });
test("whitespace error fails a real diff", () => { const f = repo({ whitespace: true }); try { const output = verifyEventDiff(f.root, { GITHUB_EVENT_NAME: "push", GITHUB_EVENT_PATH: event(f.root, { before: f.base, after: f.head }) }); assert.notEqual(output.exitCode, 0); } finally { rmSync(f.root, { recursive: true, force: true }); } });
test("malformed, missing, unsupported, and unavailable bindings fail closed", () => { const f = repo(); try { assert.throws(() => verifyEventDiff(f.root, { GITHUB_EVENT_NAME: "workflow_dispatch", GITHUB_EVENT_PATH: event(f.root, {}) }), /UNSUPPORTED/); const malformed = event(f.root, {}); writeFileSync(malformed, "{"); assert.throws(() => verifyEventDiff(f.root, { GITHUB_EVENT_NAME: "push", GITHUB_EVENT_PATH: malformed }), /INVALID_JSON/); assert.throws(() => verifyEventDiff(f.root, { GITHUB_EVENT_NAME: "push", GITHUB_EVENT_PATH: event(f.root, { before: f.base }) }), /BINDING/); assert.throws(() => verifyEventDiff(f.root, { GITHUB_EVENT_NAME: "push", GITHUB_EVENT_PATH: event(f.root, { before: "bad", after: f.head }) }), /BINDING/); assert.throws(() => verifyEventDiff(f.root, { GITHUB_EVENT_NAME: "pull_request", GITHUB_EVENT_PATH: event(f.root, { pull_request: { base: { sha: f.base }, head: { sha: "f".repeat(40) } } }) }), /OBJECT/); assert.throws(() => verifyEventDiff(f.root, { GITHUB_EVENT_NAME: "push", GITHUB_EVENT_PATH: join(f.root, "missing.json") }), /EVENT_PATH/); } finally { rmSync(f.root, { recursive: true, force: true }); } });
test("--list declares an event-bound diff, never a bare diff check", () => { const output = spawnSync(process.execPath, [runner, "--list"], { encoding: "utf8" }); assert.equal(output.status, 0, output.stderr); const text = output.stdout; assert.match(text, /real-diff-check/); assert.match(text, /GITHUB_EVENT_PATH/); assert.doesNotMatch(text, /\"git\",\[\"diff\",\"--check\"\]/); });
