import { useEffect, useRef } from "react";
import type { WorkspaceSpace } from "../../fixtures/workspace-fixtures";
import { spaceLabel, type WorkbenchItem } from "./workbench-model";

export function WorkspaceSidebar({ spaces, items, spaceId, mine, favoritesOnly, favoriteCount, expanded, homeActive, onNavigate, onSearch, onAgent, onFavorites, onClose }: { spaces: readonly WorkspaceSpace[]; items: readonly WorkbenchItem[]; spaceId: string; mine: boolean; favoritesOnly: boolean; favoriteCount: number; expanded: boolean; homeActive: boolean; onNavigate: (spaceId: string, mine: boolean) => void; onSearch: () => void; onAgent: () => void; onFavorites: () => void; onClose: () => void }) {
  const closeRef = useRef<HTMLButtonElement>(null);
  useEffect(() => { if (expanded) closeRef.current?.focus(); }, [expanded]);
  return <aside aria-label="能力空间" className={`wb-sidebar ${expanded ? "wb-sidebar-expanded" : ""}`} id="wb-sidebar"><div className="wb-brand"><span aria-hidden="true">W</span>Hospital Workspace</div><button className="wb-mobile-close" onClick={onClose} ref={closeRef} type="button">关闭侧栏</button><nav aria-label="主要导航"><button aria-current={homeActive && !spaceId && !mine && !favoritesOnly ? "page" : undefined} onClick={() => onNavigate("", false)} type="button"><span aria-hidden="true">⌂</span>首页</button><button onClick={onSearch} type="button"><span aria-hidden="true">⌕</span>搜索事项<kbd>Ctrl K</kbd></button><button aria-current={homeActive && mine ? "page" : undefined} onClick={() => onNavigate("", true)} type="button"><span aria-hidden="true">✓</span>我参与的<small>{items.filter((item) => item.mine).length}</small></button></nav><section className="wb-sidebar-group"><h2>今日安排 <small>固定示例</small></h2><p>运维事项整理 <time>09:30</time></p><p>协作背景核对 <time>14:00</time></p></section><section className="wb-sidebar-group"><h2>智能助手</h2><button onClick={onAgent} type="button"><span className="wb-space-icon" aria-hidden="true">✧</span>协作助手 <small>未接入</small></button></section><section className="wb-sidebar-group"><h2>团队空间</h2>{spaces.map((space, index) => <button aria-current={homeActive && space.id === spaceId ? "page" : undefined} key={space.id} onClick={() => onNavigate(space.id, false)} type="button"><span aria-hidden="true" className={`wb-space-icon wb-space-${index}`}>▦</span>{spaceLabel(space.label)}<small>{items.filter((item) => item.spaceId === space.id).length}</small></button>)}</section><section className="wb-sidebar-group"><h2>我的空间</h2><button aria-current={homeActive && favoritesOnly ? "page" : undefined} onClick={onFavorites} type="button"><span aria-hidden="true">☆</span>已收藏<small>{favoriteCount}</small></button></section><div className="wb-profile"><span className="wb-person-mark">S</span><div>Synthetic User<small>Example Hospital · 演示</small></div></div></aside>;
}
